# $Id$

# Purpose: Perl module for use by HITRAN programs.

# Usage: /Users/zender/sw/ck/HITRAN.pm automatically generated by htrn on Mon Oct  1 10:42:00 2018


# Command: htrn

package HITRAN;
require Exporter;
@ISA=qw(Exporter);
@EXPORT=qw($mlc_nbr_max_htrn $iso_nbr_max_htrn $iso_per_mlc_nbr_max_htrn %mlc_sng %iso_sng %mlc_iso %H2O %CO2 %O3 %N2O %CO %CH4 %O2 %NO %SO2 %NO2 %NH3 %HNO3 %OH %HF %HCl %HBr %HI %ClO %OCS %H2CO %HOCl %N2 %HCN %CH3Cl %H2O2 %C2H2 %C2H6 %PH3 %COF2 %SF6 %H2S %HCOOH %HO2 %O %ClONO2 %NO_ion %HOBr %C2H4 %CH3OH %CH3Br %CH3CN %CF4 %C4H2 %HC3N %H2 %CS %SO3 %C2N2 %COCl2 ); # Export by default
$mlc_nbr_max_htrn=49; # Number of gases in HITRAN database
$iso_nbr_max_htrn=125; # Number of isotopomers in HITRAN database
$iso_per_mlc_nbr_max_htrn=11; # Maximum number of isotopes of a molecule in HITRAN database

%mlc_sng=(
	1 => 'H2O',
	2 => 'CO2',
	3 => 'O3',
	4 => 'N2O',
	5 => 'CO',
	6 => 'CH4',
	7 => 'O2',
	8 => 'NO',
	9 => 'SO2',
	10 => 'NO2',
	11 => 'NH3',
	12 => 'HNO3',
	13 => 'OH',
	14 => 'HF',
	15 => 'HCl',
	16 => 'HBr',
	17 => 'HI',
	18 => 'ClO',
	19 => 'OCS',
	20 => 'H2CO',
	21 => 'HOCl',
	22 => 'N2',
	23 => 'HCN',
	24 => 'CH3Cl',
	25 => 'H2O2',
	26 => 'C2H2',
	27 => 'C2H6',
	28 => 'PH3',
	29 => 'COF2',
	30 => 'SF6',
	31 => 'H2S',
	32 => 'HCOOH',
	33 => 'HO2',
	34 => 'O',
	35 => 'ClONO2',
	36 => 'NO_ion',
	37 => 'HOBr',
	38 => 'C2H4',
	39 => 'CH3OH',
	40 => 'CH3Br',
	41 => 'CH3CN',
	42 => 'CF4',
	43 => 'C4H2',
	44 => 'HC3N',
	45 => 'H2',
	46 => 'CS',
	47 => 'SO3',
	48 => 'C2N2',
	49 => 'COCl2',
	); # end %mlc_sng

%iso_sng=(
	1 => '1H2_16O',
	2 => '1H2_18O',
	3 => '1H2_17O',
	4 => '1H_2H_16O',
	5 => '1H_2H_18O',
	6 => '1H_2H_17O',
	7 => '2H_2H_16O',
	8 => '12C_16O2',
	9 => '13C_16O2',
	10 => '16O_12C_18O',
	11 => '16O_12C_17O',
	12 => '16O_13C_18O',
	13 => '16O_13C_17O',
	14 => '12C_18O2',
	15 => '17O_12C_18O',
	16 => '12C_17O2',
	17 => '13C_18O2',
	18 => '18O_13C_17O',
	19 => '16O3',
	20 => '16O_16O_18O',
	21 => '16O_18O_16O',
	22 => '16O_16O_17O',
	23 => '16O_17O_16O',
	24 => '14N2_16O',
	25 => '14N_15N_16O',
	26 => '15N_14N_16O',
	27 => '14N2_18O',
	28 => '14N2_17O',
	29 => '12C_16O',
	30 => '13C_16O',
	31 => '12C_18O',
	32 => '12C_17O',
	33 => '13C_18O',
	34 => '13C_17O',
	35 => '12C_1H4',
	36 => '13C_1H4',
	37 => '12C_1H3_2H',
	38 => '13C_1H3_2H',
	39 => '16O2',
	40 => '16O_18O',
	41 => '16O_17O',
	42 => '14N_16O',
	43 => '15N_16O',
	44 => '14N_18O',
	45 => '32S_16O2',
	46 => '34S_16O2',
	47 => '14N_16O2',
	48 => '14N_1H3',
	49 => '15N_1H3',
	50 => '1H_14N_16O3',
	51 => '1H_15N_16O3',
	52 => '16O_1H',
	53 => '18O_1H',
	54 => '16O_2H',
	55 => '1H_19F',
	56 => '2H_19F',
	57 => '1H_35Cl',
	58 => '1H_37Cl',
	59 => '2H_35Cl',
	60 => '2H_37Cl',
	61 => '1H_79Br',
	62 => '1H_81Br',
	63 => '2H_79Br',
	64 => '2H_81Br',
	65 => '1H_127I',
	66 => '2H_127I',
	67 => '35Cl_16O',
	68 => '37Cl_16O',
	69 => '16O_12C_32S',
	70 => '16O_12C_34S',
	71 => '16O_13C_32S',
	72 => '16O_12C_33S',
	73 => '18O_12C_32S',
	74 => '1H2_12C_16O',
	75 => '1H2_13C_16O',
	76 => '1H2_12C_18O',
	77 => '1H_16O_35Cl',
	78 => '1H_16O_37Cl',
	79 => '14N2',
	80 => '14N_15N',
	81 => '1H_12C_14N',
	82 => '1H_13C_14N',
	83 => '1H_12C_15N',
	84 => '12C_1H_35Cl',
	85 => '12C_1H_37Cl',
	86 => '1H2_16O2',
	87 => '12C2_1H2',
	88 => '1H_12C_13C_1H',
	89 => '1H_12C_12C_2H',
	90 => '12C2_1H6',
	91 => '12C_13C_1H6',
	92 => '31P_1H3',
	93 => '12C_16O_19F2',
	94 => '13C_16O_19F2',
	95 => '32S_19F6',
	96 => '1H2_32S',
	97 => '1H_34S_1H',
	98 => '1H_33S_1H',
	99 => '1H2_12C_16O2',
	100 => '1H_16O2',
	101 => '16O',
	102 => '35Cl_16O_14N_16O2',
	103 => '37Cl_16O_14N_16O2',
	104 => '14N_16O_ion',
	105 => '1H_16O_79Br',
	106 => '1H_16O_81Br',
	107 => '12C2_1H4',
	108 => '12C_13C_1H4',
	109 => '12C2_1H3_16O_1H',
	110 => '12C_1H3_79Br',
	111 => '12C_1H3_81Br',
	112 => '12C2_1H3_14N',
	113 => '12C_F4',
	114 => '12C4_1H2',
	115 => '1H_12C3_14N',
	116 => '1H',
	117 => '2H',
	118 => '12C_32S',
	119 => '13C_32S',
	120 => '12C_34S',
	121 => '13C_34S',
	122 => '32S_16O3',
	123 => '12C2_14N2',
	124 => '12C_16O_35Cl2',
	125 => '12C_16O_35Cl_37Cl',
	); # end %iso_sng

%mlc_iso=(
	H2O => [1, 2, 3, 4, 5, 6, 7, ],
	CO2 => [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, ],
	O3 => [19, 20, 21, 22, 23, ],
	N2O => [24, 25, 26, 27, 28, ],
	CO => [29, 30, 31, 32, 33, 34, ],
	CH4 => [35, 36, 37, 38, ],
	O2 => [39, 40, 41, ],
	NO => [42, 43, 44, ],
	SO2 => [45, 46, ],
	NO2 => [47, ],
	NH3 => [48, 49, ],
	HNO3 => [50, 51, ],
	OH => [52, 53, 54, ],
	HF => [55, 56, ],
	HCl => [57, 58, 59, 60, ],
	HBr => [61, 62, 63, 64, ],
	HI => [65, 66, ],
	ClO => [67, 68, ],
	OCS => [69, 70, 71, 72, 73, ],
	H2CO => [74, 75, 76, ],
	HOCl => [77, 78, ],
	N2 => [79, 80, ],
	HCN => [81, 82, 83, ],
	CH3Cl => [84, 85, ],
	H2O2 => [86, ],
	C2H2 => [87, 88, 89, ],
	C2H6 => [90, 91, ],
	PH3 => [92, ],
	COF2 => [93, 94, ],
	SF6 => [95, ],
	H2S => [96, 97, 98, ],
	HCOOH => [99, ],
	HO2 => [100, ],
	O => [101, ],
	ClONO2 => [102, 103, ],
	NO_ion => [104, ],
	HOBr => [105, 106, ],
	C2H4 => [107, 108, ],
	CH3OH => [109, ],
	CH3Br => [110, 111, ],
	CH3CN => [112, ],
	CF4 => [113, ],
	C4H2 => [114, ],
	HC3N => [115, ],
	H2 => [116, 117, ],
	CS => [118, 119, 120, 121, ],
	SO3 => [122, ],
	C2N2 => [123, ],
	COCl2 => [124, 125, ],
	); # end %mlc_iso

%H2O=( # HITRAN molecule 1
	1 => '1H2_16O',
	2 => '1H2_18O',
	3 => '1H2_17O',
	4 => '1H_2H_16O',
	5 => '1H_2H_18O',
	6 => '1H_2H_17O',
	7 => '2H_2H_16O',
	); # end %H2O

%CO2=( # HITRAN molecule 2
	1 => '12C_16O2',
	2 => '13C_16O2',
	3 => '16O_12C_18O',
	4 => '16O_12C_17O',
	5 => '16O_13C_18O',
	6 => '16O_13C_17O',
	7 => '12C_18O2',
	8 => '17O_12C_18O',
	9 => '12C_17O2',
	10 => '13C_18O2',
	11 => '18O_13C_17O',
	); # end %CO2

%O3=( # HITRAN molecule 3
	1 => '16O3',
	2 => '16O_16O_18O',
	3 => '16O_18O_16O',
	4 => '16O_16O_17O',
	5 => '16O_17O_16O',
	); # end %O3

%N2O=( # HITRAN molecule 4
	1 => '14N2_16O',
	2 => '14N_15N_16O',
	3 => '15N_14N_16O',
	4 => '14N2_18O',
	5 => '14N2_17O',
	); # end %N2O

%CO=( # HITRAN molecule 5
	1 => '12C_16O',
	2 => '13C_16O',
	3 => '12C_18O',
	4 => '12C_17O',
	5 => '13C_18O',
	6 => '13C_17O',
	); # end %CO

%CH4=( # HITRAN molecule 6
	1 => '12C_1H4',
	2 => '13C_1H4',
	3 => '12C_1H3_2H',
	4 => '13C_1H3_2H',
	); # end %CH4

%O2=( # HITRAN molecule 7
	1 => '16O2',
	2 => '16O_18O',
	3 => '16O_17O',
	); # end %O2

%NO=( # HITRAN molecule 8
	1 => '14N_16O',
	2 => '15N_16O',
	3 => '14N_18O',
	); # end %NO

%SO2=( # HITRAN molecule 9
	1 => '32S_16O2',
	2 => '34S_16O2',
	); # end %SO2

%NO2=( # HITRAN molecule 10
	1 => '14N_16O2',
	); # end %NO2

%NH3=( # HITRAN molecule 11
	1 => '14N_1H3',
	2 => '15N_1H3',
	); # end %NH3

%HNO3=( # HITRAN molecule 12
	1 => '1H_14N_16O3',
	2 => '1H_15N_16O3',
	); # end %HNO3

%OH=( # HITRAN molecule 13
	1 => '16O_1H',
	2 => '18O_1H',
	3 => '16O_2H',
	); # end %OH

%HF=( # HITRAN molecule 14
	1 => '1H_19F',
	2 => '2H_19F',
	); # end %HF

%HCl=( # HITRAN molecule 15
	1 => '1H_35Cl',
	2 => '1H_37Cl',
	3 => '2H_35Cl',
	4 => '2H_37Cl',
	); # end %HCl

%HBr=( # HITRAN molecule 16
	1 => '1H_79Br',
	2 => '1H_81Br',
	3 => '2H_79Br',
	4 => '2H_81Br',
	); # end %HBr

%HI=( # HITRAN molecule 17
	1 => '1H_127I',
	2 => '2H_127I',
	); # end %HI

%ClO=( # HITRAN molecule 18
	1 => '35Cl_16O',
	2 => '37Cl_16O',
	); # end %ClO

%OCS=( # HITRAN molecule 19
	1 => '16O_12C_32S',
	2 => '16O_12C_34S',
	3 => '16O_13C_32S',
	4 => '16O_12C_33S',
	5 => '18O_12C_32S',
	); # end %OCS

%H2CO=( # HITRAN molecule 20
	1 => '1H2_12C_16O',
	2 => '1H2_13C_16O',
	3 => '1H2_12C_18O',
	); # end %H2CO

%HOCl=( # HITRAN molecule 21
	1 => '1H_16O_35Cl',
	2 => '1H_16O_37Cl',
	); # end %HOCl

%N2=( # HITRAN molecule 22
	1 => '14N2',
	2 => '14N_15N',
	); # end %N2

%HCN=( # HITRAN molecule 23
	1 => '1H_12C_14N',
	2 => '1H_13C_14N',
	3 => '1H_12C_15N',
	); # end %HCN

%CH3Cl=( # HITRAN molecule 24
	1 => '12C_1H_35Cl',
	2 => '12C_1H_37Cl',
	); # end %CH3Cl

%H2O2=( # HITRAN molecule 25
	1 => '1H2_16O2',
	); # end %H2O2

%C2H2=( # HITRAN molecule 26
	1 => '12C2_1H2',
	2 => '1H_12C_13C_1H',
	3 => '1H_12C_12C_2H',
	); # end %C2H2

%C2H6=( # HITRAN molecule 27
	1 => '12C2_1H6',
	2 => '12C_13C_1H6',
	); # end %C2H6

%PH3=( # HITRAN molecule 28
	1 => '31P_1H3',
	); # end %PH3

%COF2=( # HITRAN molecule 29
	1 => '12C_16O_19F2',
	2 => '13C_16O_19F2',
	); # end %COF2

%SF6=( # HITRAN molecule 30
	1 => '32S_19F6',
	); # end %SF6

%H2S=( # HITRAN molecule 31
	1 => '1H2_32S',
	2 => '1H_34S_1H',
	3 => '1H_33S_1H',
	); # end %H2S

%HCOOH=( # HITRAN molecule 32
	1 => '1H2_12C_16O2',
	); # end %HCOOH

%HO2=( # HITRAN molecule 33
	1 => '1H_16O2',
	); # end %HO2

%O=( # HITRAN molecule 34
	1 => '16O',
	); # end %O

%ClONO2=( # HITRAN molecule 35
	1 => '35Cl_16O_14N_16O2',
	2 => '37Cl_16O_14N_16O2',
	); # end %ClONO2

%NO_ion=( # HITRAN molecule 36
	1 => '14N_16O_ion',
	); # end %NO_ion

%HOBr=( # HITRAN molecule 37
	1 => '1H_16O_79Br',
	2 => '1H_16O_81Br',
	); # end %HOBr

%C2H4=( # HITRAN molecule 38
	1 => '12C2_1H4',
	2 => '12C_13C_1H4',
	); # end %C2H4

%CH3OH=( # HITRAN molecule 39
	1 => '12C2_1H3_16O_1H',
	); # end %CH3OH

%CH3Br=( # HITRAN molecule 40
	1 => '12C_1H3_79Br',
	2 => '12C_1H3_81Br',
	); # end %CH3Br

%CH3CN=( # HITRAN molecule 41
	1 => '12C2_1H3_14N',
	); # end %CH3CN

%CF4=( # HITRAN molecule 42
	1 => '12C_F4',
	); # end %CF4

%C4H2=( # HITRAN molecule 43
	1 => '12C4_1H2',
	); # end %C4H2

%HC3N=( # HITRAN molecule 44
	1 => '1H_12C3_14N',
	); # end %HC3N

%H2=( # HITRAN molecule 45
	1 => '1H',
	2 => '2H',
	); # end %H2

%CS=( # HITRAN molecule 46
	1 => '12C_32S',
	2 => '13C_32S',
	3 => '12C_34S',
	4 => '13C_34S',
	); # end %CS

%SO3=( # HITRAN molecule 47
	1 => '32S_16O3',
	); # end %SO3

%C2N2=( # HITRAN molecule 48
	1 => '12C2_14N2',
	); # end %C2N2

%COCl2=( # HITRAN molecule 49
	1 => '12C_16O_35Cl2',
	2 => '12C_16O_35Cl_37Cl',
	); # end %COCl2

