# $Id$

# Purpose: Perl module for use by HITRAN programs.

# Usage: /home/zender/ck/HITRAN.pm automatically generated by htrn on Wed Jun 12 10:58:29 2013


# Command: htrn

package HITRAN;
require Exporter;
@ISA=qw(Exporter);
@EXPORT=qw($mlc_nbr_max_htrn $iso_nbr_max_htrn $iso_per_mlc_nbr_max_htrn %mlc_sng %iso_sng %mlc_iso %H2O %CO2 %O3 %N2O %CO %CH4 %O2 %NO %SO2 %NO2 %NH3 %HNO3 %OH %HF %HCl %HBr %HI %ClO %OCS %H2CO %HOCl %N2 %HCN %CH3Cl %H2O2 %C2H2 %C2H6 %PH3 %COF2 %SF6 %H2S %HCOOH %HO2 %O %ClONO2 %NO_ion %HOBr %C2H4 %CH3OH %CH3Br %CH3CN %CF4 %C4H2 %HC3N %H2 %CS %SO3 ); # Export by default
$mlc_nbr_max_htrn=47; # Number of gases in HITRAN database
$iso_nbr_max_htrn=121; # Number of isotopomers in HITRAN database
$iso_per_mlc_nbr_max_htrn=11; # Maximum number of isotopes of a molecule in HITRAN database

%mlc_sng=(
	1 => 'H2O',
	2 => 'CO2',
	3 => 'O3',
	4 => 'N2O',
	5 => 'CO',
	6 => 'CH4',
	7 => 'O2',
	8 => 'NO',
	9 => 'SO2',
	10 => 'NO2',
	11 => 'NH3',
	12 => 'HNO3',
	13 => 'OH',
	14 => 'HF',
	15 => 'HCl',
	16 => 'HBr',
	17 => 'HI',
	18 => 'ClO',
	19 => 'OCS',
	20 => 'H2CO',
	21 => 'HOCl',
	22 => 'N2',
	23 => 'HCN',
	24 => 'CH3Cl',
	25 => 'H2O2',
	26 => 'C2H2',
	27 => 'C2H6',
	28 => 'PH3',
	29 => 'COF2',
	30 => 'SF6',
	31 => 'H2S',
	32 => 'HCOOH',
	33 => 'HO2',
	34 => 'O',
	35 => 'ClONO2',
	36 => 'NO_ion',
	37 => 'HOBr',
	38 => 'C2H4',
	39 => 'CH3OH',
	40 => 'CH3Br',
	41 => 'CH3CN',
	42 => 'CF4',
	43 => 'C4H2',
	44 => 'HC3N',
	45 => 'H2',
	46 => 'CS',
	47 => 'SO3',
	); # end %mlc_sng

%iso_sng=(
	1 => '1H2_16O',
	2 => '1H2_18O',
	3 => '1H2_17O',
	4 => '1H_2H_16O',
	5 => '1H_2H_18O',
	6 => '1H_2H_17O',
	7 => '12C_16O2',
	8 => '13C_16O2',
	9 => '16O_12C_18O',
	10 => '16O_12C_17O',
	11 => '16O_13C_18O',
	12 => '16O_13C_17O',
	13 => '12C_18O2',
	14 => '17O_12C_18O',
	15 => '12C_17O2',
	16 => '13C_18O2',
	17 => '18O_13C_17O',
	18 => '16O3',
	19 => '16O_16O_18O',
	20 => '16O_18O_16O',
	21 => '16O_16O_17O',
	22 => '16O_17O_16O',
	23 => '14N2_16O',
	24 => '14N_15N_16O',
	25 => '15N_14N_16O',
	26 => '14N2_18O',
	27 => '14N2_17O',
	28 => '12C_16O',
	29 => '13C_16O',
	30 => '12C_18O',
	31 => '12C_17O',
	32 => '13C_18O',
	33 => '13C_17O',
	34 => '12C_1H4',
	35 => '13C_1H4',
	36 => '12C_1H3_2H',
	37 => '13C_1H3_2H',
	38 => '16O2',
	39 => '16O_18O',
	40 => '16O_17O',
	41 => '14N_16O',
	42 => '15N_16O',
	43 => '14N_18O',
	44 => '32S_16O2',
	45 => '34S_16O2',
	46 => '14N_16O2',
	47 => '14N_1H3',
	48 => '15N_1H3',
	49 => '1H_14N_16O3',
	50 => '1H_15N_16O3',
	51 => '16O_1H',
	52 => '18O_1H',
	53 => '16O_2H',
	54 => '1H_19F',
	55 => '2H_19F',
	56 => '1H_35Cl',
	57 => '1H_37Cl',
	58 => '2H_35Cl',
	59 => '2H_37Cl',
	60 => '1H_79Br',
	61 => '1H_81Br',
	62 => '2H_79Br',
	63 => '2H_81Br',
	64 => '1H_127I',
	65 => '2H_127I',
	66 => '35Cl_16O',
	67 => '37Cl_16O',
	68 => '16O_12C_32S',
	69 => '16O_12C_34S',
	70 => '16O_13C_32S',
	71 => '16O_12C_33S',
	72 => '18O_12C_32S',
	73 => '1H2_12C_16O',
	74 => '1H2_13C_16O',
	75 => '1H2_12C_18O',
	76 => '1H_16O_35Cl',
	77 => '1H_16O_37Cl',
	78 => '14N2',
	79 => '14N_15N',
	80 => '1H_12C_14N',
	81 => '1H_13C_14N',
	82 => '1H_12C_15N',
	83 => '12C_1H_35Cl',
	84 => '12C_1H_37Cl',
	85 => '1H2_16O2',
	86 => '12C2_1H2',
	87 => '1H_12C_13C_1H',
	88 => '1H_12C_12C_2H',
	89 => '12C2_1H6',
	90 => '12C_13C_1H6',
	91 => '31P_1H3',
	92 => '12C_16O_19F2',
	93 => '13C_16O_19F2',
	94 => '32S_19F6',
	95 => '1H2_32S',
	96 => '1H_34S_1H',
	97 => '1H_33S_1H',
	98 => '1H2_12C_16O2',
	99 => '1H_16O2',
	100 => '16O',
	101 => '35Cl_16O_14N_16O2',
	102 => '37Cl_16O_14N_16O2',
	103 => '14N_16O_ion',
	104 => '1H_16O_79Br',
	105 => '1H_16O_81Br',
	106 => '12C2_1H4',
	107 => '12C_13C_1H4',
	108 => '12C2_1H3_16O_1H',
	109 => '12C_1H3_79Br',
	110 => '12C_1H3_81Br',
	111 => '12C2_1H3_14N',
	112 => '12C_F4',
	113 => '12C4_1H2',
	114 => '1H_12C3_14N',
	115 => '1H',
	116 => '2H',
	117 => '12C_32S',
	118 => '13C_32S',
	119 => '12C_34S',
	120 => '13C_34S',
	121 => '32S_16O3',
	); # end %iso_sng

%mlc_iso=(
	H2O => [1, 2, 3, 4, 5, 6, ],
	CO2 => [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, ],
	O3 => [18, 19, 20, 21, 22, ],
	N2O => [23, 24, 25, 26, 27, ],
	CO => [28, 29, 30, 31, 32, 33, ],
	CH4 => [34, 35, 36, 37, ],
	O2 => [38, 39, 40, ],
	NO => [41, 42, 43, ],
	SO2 => [44, 45, ],
	NO2 => [46, ],
	NH3 => [47, 48, ],
	HNO3 => [49, 50, ],
	OH => [51, 52, 53, ],
	HF => [54, 55, ],
	HCl => [56, 57, 58, 59, ],
	HBr => [60, 61, 62, 63, ],
	HI => [64, 65, ],
	ClO => [66, 67, ],
	OCS => [68, 69, 70, 71, 72, ],
	H2CO => [73, 74, 75, ],
	HOCl => [76, 77, ],
	N2 => [78, 79, ],
	HCN => [80, 81, 82, ],
	CH3Cl => [83, 84, ],
	H2O2 => [85, ],
	C2H2 => [86, 87, 88, ],
	C2H6 => [89, 90, ],
	PH3 => [91, ],
	COF2 => [92, 93, ],
	SF6 => [94, ],
	H2S => [95, 96, 97, ],
	HCOOH => [98, ],
	HO2 => [99, ],
	O => [100, ],
	ClONO2 => [101, 102, ],
	NO_ion => [103, ],
	HOBr => [104, 105, ],
	C2H4 => [106, 107, ],
	CH3OH => [108, ],
	CH3Br => [109, 110, ],
	CH3CN => [111, ],
	CF4 => [112, ],
	C4H2 => [113, ],
	HC3N => [114, ],
	H2 => [115, 116, ],
	CS => [117, 118, 119, 120, ],
	SO3 => [121, ],
	); # end %mlc_iso

%H2O=( # HITRAN molecule 1
	1 => '1H2_16O',
	2 => '1H2_18O',
	3 => '1H2_17O',
	4 => '1H_2H_16O',
	5 => '1H_2H_18O',
	6 => '1H_2H_17O',
	); # end %H2O

%CO2=( # HITRAN molecule 2
	1 => '12C_16O2',
	2 => '13C_16O2',
	3 => '16O_12C_18O',
	4 => '16O_12C_17O',
	5 => '16O_13C_18O',
	6 => '16O_13C_17O',
	7 => '12C_18O2',
	8 => '17O_12C_18O',
	9 => '12C_17O2',
	10 => '13C_18O2',
	11 => '18O_13C_17O',
	); # end %CO2

%O3=( # HITRAN molecule 3
	1 => '16O3',
	2 => '16O_16O_18O',
	3 => '16O_18O_16O',
	4 => '16O_16O_17O',
	5 => '16O_17O_16O',
	); # end %O3

%N2O=( # HITRAN molecule 4
	1 => '14N2_16O',
	2 => '14N_15N_16O',
	3 => '15N_14N_16O',
	4 => '14N2_18O',
	5 => '14N2_17O',
	); # end %N2O

%CO=( # HITRAN molecule 5
	1 => '12C_16O',
	2 => '13C_16O',
	3 => '12C_18O',
	4 => '12C_17O',
	5 => '13C_18O',
	6 => '13C_17O',
	); # end %CO

%CH4=( # HITRAN molecule 6
	1 => '12C_1H4',
	2 => '13C_1H4',
	3 => '12C_1H3_2H',
	4 => '13C_1H3_2H',
	); # end %CH4

%O2=( # HITRAN molecule 7
	1 => '16O2',
	2 => '16O_18O',
	3 => '16O_17O',
	); # end %O2

%NO=( # HITRAN molecule 8
	1 => '14N_16O',
	2 => '15N_16O',
	3 => '14N_18O',
	); # end %NO

%SO2=( # HITRAN molecule 9
	1 => '32S_16O2',
	2 => '34S_16O2',
	); # end %SO2

%NO2=( # HITRAN molecule 10
	1 => '14N_16O2',
	); # end %NO2

%NH3=( # HITRAN molecule 11
	1 => '14N_1H3',
	2 => '15N_1H3',
	); # end %NH3

%HNO3=( # HITRAN molecule 12
	1 => '1H_14N_16O3',
	2 => '1H_15N_16O3',
	); # end %HNO3

%OH=( # HITRAN molecule 13
	1 => '16O_1H',
	2 => '18O_1H',
	3 => '16O_2H',
	); # end %OH

%HF=( # HITRAN molecule 14
	1 => '1H_19F',
	2 => '2H_19F',
	); # end %HF

%HCl=( # HITRAN molecule 15
	1 => '1H_35Cl',
	2 => '1H_37Cl',
	3 => '2H_35Cl',
	4 => '2H_37Cl',
	); # end %HCl

%HBr=( # HITRAN molecule 16
	1 => '1H_79Br',
	2 => '1H_81Br',
	3 => '2H_79Br',
	4 => '2H_81Br',
	); # end %HBr

%HI=( # HITRAN molecule 17
	1 => '1H_127I',
	2 => '2H_127I',
	); # end %HI

%ClO=( # HITRAN molecule 18
	1 => '35Cl_16O',
	2 => '37Cl_16O',
	); # end %ClO

%OCS=( # HITRAN molecule 19
	1 => '16O_12C_32S',
	2 => '16O_12C_34S',
	3 => '16O_13C_32S',
	4 => '16O_12C_33S',
	5 => '18O_12C_32S',
	); # end %OCS

%H2CO=( # HITRAN molecule 20
	1 => '1H2_12C_16O',
	2 => '1H2_13C_16O',
	3 => '1H2_12C_18O',
	); # end %H2CO

%HOCl=( # HITRAN molecule 21
	1 => '1H_16O_35Cl',
	2 => '1H_16O_37Cl',
	); # end %HOCl

%N2=( # HITRAN molecule 22
	1 => '14N2',
	2 => '14N_15N',
	); # end %N2

%HCN=( # HITRAN molecule 23
	1 => '1H_12C_14N',
	2 => '1H_13C_14N',
	3 => '1H_12C_15N',
	); # end %HCN

%CH3Cl=( # HITRAN molecule 24
	1 => '12C_1H_35Cl',
	2 => '12C_1H_37Cl',
	); # end %CH3Cl

%H2O2=( # HITRAN molecule 25
	1 => '1H2_16O2',
	); # end %H2O2

%C2H2=( # HITRAN molecule 26
	1 => '12C2_1H2',
	2 => '1H_12C_13C_1H',
	3 => '1H_12C_12C_2H',
	); # end %C2H2

%C2H6=( # HITRAN molecule 27
	1 => '12C2_1H6',
	2 => '12C_13C_1H6',
	); # end %C2H6

%PH3=( # HITRAN molecule 28
	1 => '31P_1H3',
	); # end %PH3

%COF2=( # HITRAN molecule 29
	1 => '12C_16O_19F2',
	2 => '13C_16O_19F2',
	); # end %COF2

%SF6=( # HITRAN molecule 30
	1 => '32S_19F6',
	); # end %SF6

%H2S=( # HITRAN molecule 31
	1 => '1H2_32S',
	2 => '1H_34S_1H',
	3 => '1H_33S_1H',
	); # end %H2S

%HCOOH=( # HITRAN molecule 32
	1 => '1H2_12C_16O2',
	); # end %HCOOH

%HO2=( # HITRAN molecule 33
	1 => '1H_16O2',
	); # end %HO2

%O=( # HITRAN molecule 34
	1 => '16O',
	); # end %O

%ClONO2=( # HITRAN molecule 35
	1 => '35Cl_16O_14N_16O2',
	2 => '37Cl_16O_14N_16O2',
	); # end %ClONO2

%NO_ion=( # HITRAN molecule 36
	1 => '14N_16O_ion',
	); # end %NO_ion

%HOBr=( # HITRAN molecule 37
	1 => '1H_16O_79Br',
	2 => '1H_16O_81Br',
	); # end %HOBr

%C2H4=( # HITRAN molecule 38
	1 => '12C2_1H4',
	2 => '12C_13C_1H4',
	); # end %C2H4

%CH3OH=( # HITRAN molecule 39
	1 => '12C2_1H3_16O_1H',
	); # end %CH3OH

%CH3Br=( # HITRAN molecule 40
	1 => '12C_1H3_79Br',
	2 => '12C_1H3_81Br',
	); # end %CH3Br

%CH3CN=( # HITRAN molecule 41
	1 => '12C2_1H3_14N',
	); # end %CH3CN

%CF4=( # HITRAN molecule 42
	1 => '12C_F4',
	); # end %CF4

%C4H2=( # HITRAN molecule 43
	1 => '12C4_1H2',
	); # end %C4H2

%HC3N=( # HITRAN molecule 44
	1 => '1H_12C3_14N',
	); # end %HC3N

%H2=( # HITRAN molecule 45
	1 => '1H',
	2 => '2H',
	); # end %H2

%CS=( # HITRAN molecule 46
	1 => '12C_32S',
	2 => '13C_32S',
	3 => '12C_34S',
	4 => '13C_34S',
	); # end %CS

%SO3=( # HITRAN molecule 47
	1 => '32S_16O3',
	); # end %SO3

