# $Id$ -*-shell-script-*-

# Purpose: Commands executed at login to a bash shell

# 20000307 It is incorrect to use ~ instead of ${HOME} in bash_profile
# Using ~ instead of ${HOME} in bashrc appears to be fine
# Is this because ${HOME} is not set until login completes?
# 20140529 Mac OS X terminal is a login shell so executes .bash_profile not .bashrc

# Source: Customized from Redhat 6.0 bash_profile

# Bash login shells execute one of (in order) .bash_profile, .bash_login, .profile
# .bashrc is executed at the start of any subshell
# .bash_logout is executed every time a Bash login shell exits

# Get aliases and functions
if [ -f ${HOME}/.bashrc ]; then
# fxm: It is unclear to me whether bashrc should be explicitly sourced here, 
# or whether the login process does this itself
    . ${HOME}/.bashrc
fi # endif bashrc

# User specific environment and startup programs
PATH=${PATH}:${HOME}/bin
BASH_ENV=${HOME}/.bashrc
USERNAME=""

export USERNAME BASH_ENV PATH

# Programs to start automatically on login, e.g., X, would go here
# startx

# 20181201: Added by Anaconda3 5.3.1 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/zender/anaconda/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/Users/zender/anaconda/etc/profile.d/conda.sh" ]; then
        . "/Users/zender/anaconda/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/Users/zender/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
