! $Id$

! Purpose: HITRAN constants and subroutines used by radiative transfer programs swnb, nbm, ck, lbl

! Copyright (C) 1994--2018 Charlie Zender
! This software is distributed under the terms of the GNU General Public License (GPL) Version 3
! See http://www.gnu.org/copyleft/gpl.html for full license text

! Compilation: 
! pgf90 -c -fast -Mextend -Mnosecond_underscore -mp -byteswapio -Mrecursive -Mdalign -DLINUX -I. -I${HOME}/include -Di386 -I/usr/local/include -o ${HOME}/obj/LINUX/hitran.o /Users/zender/sw/f/htrn_mdl.F90
! f90 -c -xs -stackvar -e  -fast -DSUNMP -I. -I${HOME}/include -I/contrib/include  -o ${HOME}/SUNMP/hitran.o /Users/zender/sw/f/htrn_mdl.F90
! f90 -cpp -c -64 -mips4 -extend_source -mp -mpio -O2 -DSGIMP64 -I. -I${HOME}/include -I/usr/local/include -o ${HOME}/obj/SGIMP64/hitran.o /Users/zender/sw/f/htrn_mdl.F90

! Generation: /Users/zender/sw/f/htrn_mdl.F90 automatically generated by htrn on Mon Oct  1 10:42:00 2018

! Command: htrn

! Usage:
! use htrn_mdl ! [mdl] HITRAN constants, subroutines

module htrn_mdl

  implicit none

  ! Dimensions of molecular database arrays
  integer,parameter::mlc_nbr_max_htrn=49 ! Number of gases in HITRAN database
  integer,parameter::iso_nbr_max_htrn=125 ! Number of isotopomers in HITRAN database
  integer,parameter::iso_per_mlc_nbr_max_htrn=11 ! Maximum number of isotopes of a molecule in HITRAN database
! Define mean molecular weight in SI units instead of g mol-1
! This keeps Avagadro's number fixed and gets rid of many factors of 1000.0

  real,parameter::mmw_H2O=1.8015261e-02 ! [kg mol-1] mmw of H2O
  real,parameter::mmw_CO2=4.4009743e-02 ! [kg mol-1] mmw of CO2
  real,parameter::mmw_O3=4.7997832e-02 ! [kg mol-1] mmw of O3
  real,parameter::mmw_N2O=4.4012674e-02 ! [kg mol-1] mmw of N2O
  real,parameter::mmw_CO=2.8010445e-02 ! [kg mol-1] mmw of CO
  real,parameter::mmw_CH4=1.6043074e-02 ! [kg mol-1] mmw of CH4
  real,parameter::mmw_O2=3.1998575e-02 ! [kg mol-1] mmw of O2
  real,parameter::mmw_NO=3.0005630e-02 ! [kg mol-1] mmw of NO
  real,parameter::mmw_SO2=6.4046674e-02 ! [kg mol-1] mmw of SO2
  real,parameter::mmw_NO2=4.5992904e-02 ! [kg mol-1] mmw of NO2
  real,parameter::mmw_NH3=1.7030201e-02 ! [kg mol-1] mmw of NH3
  real,parameter::mmw_HNO3=6.2999296e-02 ! [kg mol-1] mmw of HNO3
  real,parameter::mmw_OH=1.7006907e-02 ! [kg mol-1] mmw of OH
  real,parameter::mmw_HF=2.0006386e-02 ! [kg mol-1] mmw of HF
  real,parameter::mmw_HCl=3.6460710e-02 ! [kg mol-1] mmw of HCl
  real,parameter::mmw_HBr=8.0911588e-02 ! [kg mol-1] mmw of HBr
  real,parameter::mmw_HI=1.2791245e-01 ! [kg mol-1] mmw of HI
  real,parameter::mmw_ClO=5.1447643e-02 ! [kg mol-1] mmw of ClO
  real,parameter::mmw_OCS=6.0071832e-02 ! [kg mol-1] mmw of OCS
  real,parameter::mmw_H2CO=3.0025657e-02 ! [kg mol-1] mmw of H2CO
  real,parameter::mmw_HOCl=5.2455469e-02 ! [kg mol-1] mmw of HOCl
  real,parameter::mmw_N2=2.8013603e-02 ! [kg mol-1] mmw of N2
  real,parameter::mmw_HCN=2.7025618e-02 ! [kg mol-1] mmw of HCN
  real,parameter::mmw_CH3Cl=5.0476203e-02 ! [kg mol-1] mmw of CH3Cl
  real,parameter::mmw_H2O2=3.4005480e-02 ! [kg mol-1] mmw of H2O2
  real,parameter::mmw_C2H2=2.6037999e-02 ! [kg mol-1] mmw of C2H2
  real,parameter::mmw_C2H6=3.0069000e-02 ! [kg mol-1] mmw of C2H6
  real,parameter::mmw_PH3=3.3997238e-02 ! [kg mol-1] mmw of PH3
  real,parameter::mmw_COF2=6.6002869e-02 ! [kg mol-1] mmw of COF2
  real,parameter::mmw_SF6=1.4596249e-01 ! [kg mol-1] mmw of SF6
  real,parameter::mmw_H2S=3.4079355e-02 ! [kg mol-1] mmw of H2S
  real,parameter::mmw_HCOOH=4.6005480e-02 ! [kg mol-1] mmw of HCOOH
  real,parameter::mmw_HO2=3.2997655e-02 ! [kg mol-1] mmw of HO2
  real,parameter::mmw_O=1.5994915e-02 ! [kg mol-1] mmw of O
  real,parameter::mmw_ClONO2=9.7440548e-02 ! [kg mol-1] mmw of ClONO2
  real,parameter::mmw_NO_ion=2.9997989e-02 ! [kg mol-1] mmw of NO+
  real,parameter::mmw_HOBr=9.6906346e-02 ! [kg mol-1] mmw of HOBr
  real,parameter::mmw_C2H4=2.8053350e-02 ! [kg mol-1] mmw of C2H4
  real,parameter::mmw_CH3OH=3.2026215e-02 ! [kg mol-1] mmw of CH3OH
  real,parameter::mmw_CH3Br=9.4927081e-02 ! [kg mol-1] mmw of CH3Br
  real,parameter::mmw_CH3CN=4.1026549e-02 ! [kg mol-1] mmw of CH3CN
  real,parameter::mmw_CF4=8.7993616e-02 ! [kg mol-1] mmw of CF4
  real,parameter::mmw_C4H2=5.0015650e-02 ! [kg mol-1] mmw of C4H2
  real,parameter::mmw_HC3N=5.1010899e-02 ! [kg mol-1] mmw of HC3N
  real,parameter::mmw_H2=2.0159634e-03 ! [kg mol-1] mmw of H2
  real,parameter::mmw_CS=4.4072299e-02 ! [kg mol-1] mmw of CS
  real,parameter::mmw_SO3=7.9956820e-02 ! [kg mol-1] mmw of SO3
  real,parameter::mmw_C2N2=5.2006148e-02 ! [kg mol-1] mmw of C2N2
  real,parameter::mmw_COCl2=9.8711621e-02 ! [kg mol-1] mmw of COCl2

  real,parameter::mmw_1H2_16O=1.8010565e-02 ! [kg mol-1] mmw of H2O isotope 1, 1H2_16O
  real,parameter::mmw_1H2_18O=2.0014811e-02 ! [kg mol-1] mmw of H2O isotope 2, 1H2_18O
  real,parameter::mmw_1H2_17O=1.9014780e-02 ! [kg mol-1] mmw of H2O isotope 3, 1H2_17O
  real,parameter::mmw_1H_2H_16O=1.9016740e-02 ! [kg mol-1] mmw of H2O isotope 4, 1H_2H_16O
  real,parameter::mmw_1H_2H_18O=2.1020985e-02 ! [kg mol-1] mmw of H2O isotope 5, 1H_2H_18O
  real,parameter::mmw_1H_2H_17O=2.0020956e-02 ! [kg mol-1] mmw of H2O isotope 6, 1H_2H_17O
  real,parameter::mmw_2H_2H_16O=2.0022915e-02 ! [kg mol-1] mmw of H2O isotope 7, 2H_2H_16O
  real,parameter::mmw_12C_16O2=4.3989830e-02 ! [kg mol-1] mmw of CO2 isotope 1, 12C_16O2
  real,parameter::mmw_13C_16O2=4.4993185e-02 ! [kg mol-1] mmw of CO2 isotope 2, 13C_16O2
  real,parameter::mmw_16O_12C_18O=4.5994076e-02 ! [kg mol-1] mmw of CO2 isotope 3, 16O_12C_18O
  real,parameter::mmw_16O_12C_17O=4.4994045e-02 ! [kg mol-1] mmw of CO2 isotope 4, 16O_12C_17O
  real,parameter::mmw_16O_13C_18O=4.6997431e-02 ! [kg mol-1] mmw of CO2 isotope 5, 16O_13C_18O
  real,parameter::mmw_16O_13C_17O=4.5997400e-02 ! [kg mol-1] mmw of CO2 isotope 6, 16O_13C_17O
  real,parameter::mmw_12C_18O2=4.7998322e-02 ! [kg mol-1] mmw of CO2 isotope 7, 12C_18O2
  real,parameter::mmw_17O_12C_18O=4.6998291e-02 ! [kg mol-1] mmw of CO2 isotope 8, 17O_12C_18O
  real,parameter::mmw_12C_17O2=4.5998262e-02 ! [kg mol-1] mmw of CO2 isotope 9, 12C_17O2
  real,parameter::mmw_13C_18O2=4.9001675e-02 ! [kg mol-1] mmw of CO2 isotope 10, 13C_18O2
  real,parameter::mmw_18O_13C_17O=4.8001646e-02 ! [kg mol-1] mmw of CO2 isotope 11, 18O_13C_17O
  real,parameter::mmw_16O3=4.7984745e-02 ! [kg mol-1] mmw of O3 isotope 1, 16O3
  real,parameter::mmw_16O_16O_18O=4.9988991e-02 ! [kg mol-1] mmw of O3 isotope 2, 16O_16O_18O
  real,parameter::mmw_16O_18O_16O=4.9988991e-02 ! [kg mol-1] mmw of O3 isotope 3, 16O_18O_16O
  real,parameter::mmw_16O_16O_17O=4.8988960e-02 ! [kg mol-1] mmw of O3 isotope 4, 16O_16O_17O
  real,parameter::mmw_16O_17O_16O=4.8988960e-02 ! [kg mol-1] mmw of O3 isotope 5, 16O_17O_16O
  real,parameter::mmw_14N2_16O=4.4001062e-02 ! [kg mol-1] mmw of N2O isotope 1, 14N2_16O
  real,parameter::mmw_14N_15N_16O=4.4998096e-02 ! [kg mol-1] mmw of N2O isotope 2, 14N_15N_16O
  real,parameter::mmw_15N_14N_16O=4.4998096e-02 ! [kg mol-1] mmw of N2O isotope 3, 15N_14N_16O
  real,parameter::mmw_14N2_18O=4.6005308e-02 ! [kg mol-1] mmw of N2O isotope 4, 14N2_18O
  real,parameter::mmw_14N2_17O=4.5005278e-02 ! [kg mol-1] mmw of N2O isotope 5, 14N2_17O
  real,parameter::mmw_12C_16O=2.7994915e-02 ! [kg mol-1] mmw of CO isotope 1, 12C_16O
  real,parameter::mmw_13C_16O=2.8998270e-02 ! [kg mol-1] mmw of CO isotope 2, 13C_16O
  real,parameter::mmw_12C_18O=2.9999161e-02 ! [kg mol-1] mmw of CO isotope 3, 12C_18O
  real,parameter::mmw_12C_17O=2.8999130e-02 ! [kg mol-1] mmw of CO isotope 4, 12C_17O
  real,parameter::mmw_13C_18O=3.1002516e-02 ! [kg mol-1] mmw of CO isotope 5, 13C_18O
  real,parameter::mmw_13C_17O=3.0002485e-02 ! [kg mol-1] mmw of CO isotope 6, 13C_17O
  real,parameter::mmw_12C_1H4=1.6031300e-02 ! [kg mol-1] mmw of CH4 isotope 1, 12C_1H4
  real,parameter::mmw_13C_1H4=1.7034655e-02 ! [kg mol-1] mmw of CH4 isotope 2, 13C_1H4
  real,parameter::mmw_12C_1H3_2H=1.7037475e-02 ! [kg mol-1] mmw of CH4 isotope 3, 12C_1H3_2H
  real,parameter::mmw_13C_1H3_2H=1.8040830e-02 ! [kg mol-1] mmw of CH4 isotope 4, 13C_1H3_2H
  real,parameter::mmw_16O2=3.1989830e-02 ! [kg mol-1] mmw of O2 isotope 1, 16O2
  real,parameter::mmw_16O_18O=3.3994076e-02 ! [kg mol-1] mmw of O2 isotope 2, 16O_18O
  real,parameter::mmw_16O_17O=3.2994045e-02 ! [kg mol-1] mmw of O2 isotope 3, 16O_17O
  real,parameter::mmw_14N_16O=2.9997989e-02 ! [kg mol-1] mmw of NO isotope 1, 14N_16O
  real,parameter::mmw_15N_16O=3.0995023e-02 ! [kg mol-1] mmw of NO isotope 2, 15N_16O
  real,parameter::mmw_14N_18O=3.2002234e-02 ! [kg mol-1] mmw of NO isotope 3, 14N_18O
  real,parameter::mmw_32S_16O2=6.3961901e-02 ! [kg mol-1] mmw of SO2 isotope 1, 32S_16O2
  real,parameter::mmw_34S_16O2=6.5957695e-02 ! [kg mol-1] mmw of SO2 isotope 2, 34S_16O2
  real,parameter::mmw_14N_16O2=4.5992904e-02 ! [kg mol-1] mmw of NO2 isotope 1, 14N_16O2
  real,parameter::mmw_14N_1H3=1.7026549e-02 ! [kg mol-1] mmw of NH3 isotope 1, 14N_1H3
  real,parameter::mmw_15N_1H3=1.8023583e-02 ! [kg mol-1] mmw of NH3 isotope 2, 15N_1H3
  real,parameter::mmw_1H_14N_16O3=6.2995644e-02 ! [kg mol-1] mmw of HNO3 isotope 1, 1H_14N_16O3
  real,parameter::mmw_1H_15N_16O3=6.3992680e-02 ! [kg mol-1] mmw of HNO3 isotope 2, 1H_15N_16O3
  real,parameter::mmw_16O_1H=1.7002740e-02 ! [kg mol-1] mmw of OH isotope 1, 16O_1H
  real,parameter::mmw_18O_1H=1.9006986e-02 ! [kg mol-1] mmw of OH isotope 2, 18O_1H
  real,parameter::mmw_16O_2H=1.8008915e-02 ! [kg mol-1] mmw of OH isotope 3, 16O_2H
  real,parameter::mmw_1H_19F=2.0006229e-02 ! [kg mol-1] mmw of HF isotope 1, 1H_19F
  real,parameter::mmw_2H_19F=2.1012404e-02 ! [kg mol-1] mmw of HF isotope 2, 2H_19F
  real,parameter::mmw_1H_35Cl=3.5976678e-02 ! [kg mol-1] mmw of HCl isotope 1, 1H_35Cl
  real,parameter::mmw_1H_37Cl=3.7973729e-02 ! [kg mol-1] mmw of HCl isotope 2, 1H_37Cl
  real,parameter::mmw_2H_35Cl=3.6982853e-02 ! [kg mol-1] mmw of HCl isotope 3, 2H_35Cl
  real,parameter::mmw_2H_37Cl=3.8979904e-02 ! [kg mol-1] mmw of HCl isotope 4, 2H_37Cl
  real,parameter::mmw_1H_79Br=7.9926160e-02 ! [kg mol-1] mmw of HBr isotope 1, 1H_79Br
  real,parameter::mmw_1H_81Br=8.1924115e-02 ! [kg mol-1] mmw of HBr isotope 2, 1H_81Br
  real,parameter::mmw_2H_79Br=8.0932336e-02 ! [kg mol-1] mmw of HBr isotope 3, 2H_79Br
  real,parameter::mmw_2H_81Br=8.2930289e-02 ! [kg mol-1] mmw of HBr isotope 4, 2H_81Br
  real,parameter::mmw_1H_127I=1.2791230e-01 ! [kg mol-1] mmw of HI isotope 1, 1H_127I
  real,parameter::mmw_2H_127I=1.2891847e-01 ! [kg mol-1] mmw of HI isotope 2, 2H_127I
  real,parameter::mmw_35Cl_16O=5.0963768e-02 ! [kg mol-1] mmw of ClO isotope 1, 35Cl_16O
  real,parameter::mmw_37Cl_16O=5.2960819e-02 ! [kg mol-1] mmw of ClO isotope 2, 37Cl_16O
  real,parameter::mmw_16O_12C_32S=5.9966986e-02 ! [kg mol-1] mmw of OCS isotope 1, 16O_12C_32S
  real,parameter::mmw_16O_12C_34S=6.1962780e-02 ! [kg mol-1] mmw of OCS isotope 2, 16O_12C_34S
  real,parameter::mmw_16O_13C_32S=6.0970341e-02 ! [kg mol-1] mmw of OCS isotope 3, 16O_13C_32S
  real,parameter::mmw_16O_12C_33S=6.0966371e-02 ! [kg mol-1] mmw of OCS isotope 4, 16O_12C_33S
  real,parameter::mmw_18O_12C_32S=6.1971231e-02 ! [kg mol-1] mmw of OCS isotope 5, 18O_12C_32S
  real,parameter::mmw_1H2_12C_16O=3.0010565e-02 ! [kg mol-1] mmw of H2CO isotope 1, 1H2_12C_16O
  real,parameter::mmw_1H2_13C_16O=3.1013920e-02 ! [kg mol-1] mmw of H2CO isotope 2, 1H2_13C_16O
  real,parameter::mmw_1H2_12C_18O=3.2014811e-02 ! [kg mol-1] mmw of H2CO isotope 3, 1H2_12C_18O
  real,parameter::mmw_1H_16O_35Cl=5.1971593e-02 ! [kg mol-1] mmw of HOCl isotope 1, 1H_16O_35Cl
  real,parameter::mmw_1H_16O_37Cl=5.3968644e-02 ! [kg mol-1] mmw of HOCl isotope 2, 1H_16O_37Cl
  real,parameter::mmw_14N2=2.8006148e-02 ! [kg mol-1] mmw of N2 isotope 1, 14N2
  real,parameter::mmw_14N_15N=2.9003182e-02 ! [kg mol-1] mmw of N2 isotope 2, 14N_15N
  real,parameter::mmw_1H_12C_14N=2.7010899e-02 ! [kg mol-1] mmw of HCN isotope 1, 1H_12C_14N
  real,parameter::mmw_1H_13C_14N=2.8014254e-02 ! [kg mol-1] mmw of HCN isotope 2, 1H_13C_14N
  real,parameter::mmw_1H_12C_15N=2.8007933e-02 ! [kg mol-1] mmw of HCN isotope 3, 1H_12C_15N
  real,parameter::mmw_12C_1H_35Cl=4.9992328e-02 ! [kg mol-1] mmw of CH3Cl isotope 1, 12C_1H_35Cl
  real,parameter::mmw_12C_1H_37Cl=5.1989379e-02 ! [kg mol-1] mmw of CH3Cl isotope 2, 12C_1H_37Cl
  real,parameter::mmw_1H2_16O2=3.4005480e-02 ! [kg mol-1] mmw of H2O2 isotope 1, 1H2_16O2
  real,parameter::mmw_12C2_1H2=2.6015650e-02 ! [kg mol-1] mmw of C2H2 isotope 1, 12C2_1H2
  real,parameter::mmw_1H_12C_13C_1H=2.7019005e-02 ! [kg mol-1] mmw of C2H2 isotope 2, 1H_12C_13C_1H
  real,parameter::mmw_1H_12C_12C_2H=2.7021825e-02 ! [kg mol-1] mmw of C2H2 isotope 3, 1H_12C_12C_2H
  real,parameter::mmw_12C2_1H6=3.0046950e-02 ! [kg mol-1] mmw of C2H6 isotope 1, 12C2_1H6
  real,parameter::mmw_12C_13C_1H6=3.1050305e-02 ! [kg mol-1] mmw of C2H6 isotope 2, 12C_13C_1H6
  real,parameter::mmw_31P_1H3=3.3997238e-02 ! [kg mol-1] mmw of PH3 isotope 1, 31P_1H3
  real,parameter::mmw_12C_16O_19F2=6.5991722e-02 ! [kg mol-1] mmw of COF2 isotope 1, 12C_16O_19F2
  real,parameter::mmw_13C_16O_19F2=6.6995083e-02 ! [kg mol-1] mmw of COF2 isotope 2, 13C_16O_19F2
  real,parameter::mmw_32S_19F6=1.4596249e-01 ! [kg mol-1] mmw of SF6 isotope 1, 32S_19F6
  real,parameter::mmw_1H2_32S=3.3987721e-02 ! [kg mol-1] mmw of H2S isotope 1, 1H2_32S
  real,parameter::mmw_1H_34S_1H=3.5983515e-02 ! [kg mol-1] mmw of H2S isotope 2, 1H_34S_1H
  real,parameter::mmw_1H_33S_1H=3.4987105e-02 ! [kg mol-1] mmw of H2S isotope 3, 1H_33S_1H
  real,parameter::mmw_1H2_12C_16O2=4.6005480e-02 ! [kg mol-1] mmw of HCOOH isotope 1, 1H2_12C_16O2
  real,parameter::mmw_1H_16O2=3.2997655e-02 ! [kg mol-1] mmw of HO2 isotope 1, 1H_16O2
  real,parameter::mmw_16O=1.5994915e-02 ! [kg mol-1] mmw of O isotope 1, 16O
  real,parameter::mmw_35Cl_16O_14N_16O2=9.6956672e-02 ! [kg mol-1] mmw of ClONO2 isotope 1, 35Cl_16O_14N_16O2
  real,parameter::mmw_37Cl_16O_14N_16O2=9.8953723e-02 ! [kg mol-1] mmw of ClONO2 isotope 2, 37Cl_16O_14N_16O2
  real,parameter::mmw_14N_16O_ion=2.9997989e-02 ! [kg mol-1] mmw of NO+ isotope 1, 14N_16O+
  real,parameter::mmw_1H_16O_79Br=9.5921076e-02 ! [kg mol-1] mmw of HOBr isotope 1, 1H_16O_79Br
  real,parameter::mmw_1H_16O_81Br=9.7919027e-02 ! [kg mol-1] mmw of HOBr isotope 2, 1H_16O_81Br
  real,parameter::mmw_12C2_1H4=2.8031300e-02 ! [kg mol-1] mmw of C2H4 isotope 1, 12C2_1H4
  real,parameter::mmw_12C_13C_1H4=2.9034655e-02 ! [kg mol-1] mmw of C2H4 isotope 2, 12C_13C_1H4
  real,parameter::mmw_12C2_1H3_16O_1H=3.2026215e-02 ! [kg mol-1] mmw of CH3OH isotope 1, 12C2_1H3_16O_1H
  real,parameter::mmw_12C_1H3_79Br=9.3941811e-02 ! [kg mol-1] mmw of CH3Br isotope 1, 12C_1H3_79Br
  real,parameter::mmw_12C_1H3_81Br=9.5939764e-02 ! [kg mol-1] mmw of CH3Br isotope 2, 12C_1H3_81Br
  real,parameter::mmw_12C2_1H3_14N=4.1026549e-02 ! [kg mol-1] mmw of CH3CN isotope 1, 12C2_1H3_14N
  real,parameter::mmw_12C_F4=8.7993616e-02 ! [kg mol-1] mmw of CF4 isotope 1, 12C_F4
  real,parameter::mmw_12C4_1H2=5.0015650e-02 ! [kg mol-1] mmw of C4H2 isotope 1, 12C4_1H2
  real,parameter::mmw_1H_12C3_14N=5.1010899e-02 ! [kg mol-1] mmw of HC3N isotope 1, 1H_12C3_14N
  real,parameter::mmw_1H=2.0156500e-03 ! [kg mol-1] mmw of H2 isotope 1, 1H
  real,parameter::mmw_2H=3.0218250e-03 ! [kg mol-1] mmw of H2 isotope 2, 2H
  real,parameter::mmw_12C_32S=4.3971036e-02 ! [kg mol-1] mmw of CS isotope 1, 12C_32S
  real,parameter::mmw_13C_32S=4.5966787e-02 ! [kg mol-1] mmw of CS isotope 2, 13C_32S
  real,parameter::mmw_12C_34S=4.4974368e-02 ! [kg mol-1] mmw of CS isotope 3, 12C_34S
  real,parameter::mmw_13C_34S=4.4970399e-02 ! [kg mol-1] mmw of CS isotope 4, 13C_34S
  real,parameter::mmw_32S_16O3=7.9956820e-02 ! [kg mol-1] mmw of SO3 isotope 1, 32S_16O3
  real,parameter::mmw_12C2_14N2=5.2006148e-02 ! [kg mol-1] mmw of C2N2 isotope 1, 12C2_14N2
  real,parameter::mmw_12C_16O_35Cl2=9.7932620e-02 ! [kg mol-1] mmw of COCl2 isotope 1, 12C_16O_35Cl2
  real,parameter::mmw_12C_16O_35Cl_37Cl=9.9929670e-02 ! [kg mol-1] mmw of COCl2 isotope 2, 12C_16O_35Cl_37Cl

! Integer Fortran (1-based) indices for all HITRAN molecules

  integer,parameter::idx_H2O=1 ! [idx] HITRAN molecule number for H2O
  integer,parameter::idx_CO2=2 ! [idx] HITRAN molecule number for CO2
  integer,parameter::idx_O3=3 ! [idx] HITRAN molecule number for O3
  integer,parameter::idx_N2O=4 ! [idx] HITRAN molecule number for N2O
  integer,parameter::idx_CO=5 ! [idx] HITRAN molecule number for CO
  integer,parameter::idx_CH4=6 ! [idx] HITRAN molecule number for CH4
  integer,parameter::idx_O2=7 ! [idx] HITRAN molecule number for O2
  integer,parameter::idx_NO=8 ! [idx] HITRAN molecule number for NO
  integer,parameter::idx_SO2=9 ! [idx] HITRAN molecule number for SO2
  integer,parameter::idx_NO2=10 ! [idx] HITRAN molecule number for NO2
  integer,parameter::idx_NH3=11 ! [idx] HITRAN molecule number for NH3
  integer,parameter::idx_HNO3=12 ! [idx] HITRAN molecule number for HNO3
  integer,parameter::idx_OH=13 ! [idx] HITRAN molecule number for OH
  integer,parameter::idx_HF=14 ! [idx] HITRAN molecule number for HF
  integer,parameter::idx_HCl=15 ! [idx] HITRAN molecule number for HCl
  integer,parameter::idx_HBr=16 ! [idx] HITRAN molecule number for HBr
  integer,parameter::idx_HI=17 ! [idx] HITRAN molecule number for HI
  integer,parameter::idx_ClO=18 ! [idx] HITRAN molecule number for ClO
  integer,parameter::idx_OCS=19 ! [idx] HITRAN molecule number for OCS
  integer,parameter::idx_H2CO=20 ! [idx] HITRAN molecule number for H2CO
  integer,parameter::idx_HOCl=21 ! [idx] HITRAN molecule number for HOCl
  integer,parameter::idx_N2=22 ! [idx] HITRAN molecule number for N2
  integer,parameter::idx_HCN=23 ! [idx] HITRAN molecule number for HCN
  integer,parameter::idx_CH3Cl=24 ! [idx] HITRAN molecule number for CH3Cl
  integer,parameter::idx_H2O2=25 ! [idx] HITRAN molecule number for H2O2
  integer,parameter::idx_C2H2=26 ! [idx] HITRAN molecule number for C2H2
  integer,parameter::idx_C2H6=27 ! [idx] HITRAN molecule number for C2H6
  integer,parameter::idx_PH3=28 ! [idx] HITRAN molecule number for PH3
  integer,parameter::idx_COF2=29 ! [idx] HITRAN molecule number for COF2
  integer,parameter::idx_SF6=30 ! [idx] HITRAN molecule number for SF6
  integer,parameter::idx_H2S=31 ! [idx] HITRAN molecule number for H2S
  integer,parameter::idx_HCOOH=32 ! [idx] HITRAN molecule number for HCOOH
  integer,parameter::idx_HO2=33 ! [idx] HITRAN molecule number for HO2
  integer,parameter::idx_O=34 ! [idx] HITRAN molecule number for O
  integer,parameter::idx_ClONO2=35 ! [idx] HITRAN molecule number for ClONO2
  integer,parameter::idx_NO_ion=36 ! [idx] HITRAN molecule number for NO+
  integer,parameter::idx_HOBr=37 ! [idx] HITRAN molecule number for HOBr
  integer,parameter::idx_C2H4=38 ! [idx] HITRAN molecule number for C2H4
  integer,parameter::idx_CH3OH=39 ! [idx] HITRAN molecule number for CH3OH
  integer,parameter::idx_CH3Br=40 ! [idx] HITRAN molecule number for CH3Br
  integer,parameter::idx_CH3CN=41 ! [idx] HITRAN molecule number for CH3CN
  integer,parameter::idx_CF4=42 ! [idx] HITRAN molecule number for CF4
  integer,parameter::idx_C4H2=43 ! [idx] HITRAN molecule number for C4H2
  integer,parameter::idx_HC3N=44 ! [idx] HITRAN molecule number for HC3N
  integer,parameter::idx_H2=45 ! [idx] HITRAN molecule number for H2
  integer,parameter::idx_CS=46 ! [idx] HITRAN molecule number for CS
  integer,parameter::idx_SO3=47 ! [idx] HITRAN molecule number for SO3
  integer,parameter::idx_C2N2=48 ! [idx] HITRAN molecule number for C2N2
  integer,parameter::idx_COCl2=49 ! [idx] HITRAN molecule number for COCl2

! Integer Fortran (1-based) indices for all HITRAN isotopomers

  integer,parameter::idx_1H2_16O=1 ! [idx] HITRAN isotopomer number for H2O isotope 1, 1H2_16O
  integer,parameter::idx_1H2_18O=2 ! [idx] HITRAN isotopomer number for H2O isotope 2, 1H2_18O
  integer,parameter::idx_1H2_17O=3 ! [idx] HITRAN isotopomer number for H2O isotope 3, 1H2_17O
  integer,parameter::idx_1H_2H_16O=4 ! [idx] HITRAN isotopomer number for H2O isotope 4, 1H_2H_16O
  integer,parameter::idx_1H_2H_18O=5 ! [idx] HITRAN isotopomer number for H2O isotope 5, 1H_2H_18O
  integer,parameter::idx_1H_2H_17O=6 ! [idx] HITRAN isotopomer number for H2O isotope 6, 1H_2H_17O
  integer,parameter::idx_2H_2H_16O=7 ! [idx] HITRAN isotopomer number for H2O isotope 7, 2H_2H_16O
  integer,parameter::idx_12C_16O2=8 ! [idx] HITRAN isotopomer number for CO2 isotope 1, 12C_16O2
  integer,parameter::idx_13C_16O2=9 ! [idx] HITRAN isotopomer number for CO2 isotope 2, 13C_16O2
  integer,parameter::idx_16O_12C_18O=10 ! [idx] HITRAN isotopomer number for CO2 isotope 3, 16O_12C_18O
  integer,parameter::idx_16O_12C_17O=11 ! [idx] HITRAN isotopomer number for CO2 isotope 4, 16O_12C_17O
  integer,parameter::idx_16O_13C_18O=12 ! [idx] HITRAN isotopomer number for CO2 isotope 5, 16O_13C_18O
  integer,parameter::idx_16O_13C_17O=13 ! [idx] HITRAN isotopomer number for CO2 isotope 6, 16O_13C_17O
  integer,parameter::idx_12C_18O2=14 ! [idx] HITRAN isotopomer number for CO2 isotope 7, 12C_18O2
  integer,parameter::idx_17O_12C_18O=15 ! [idx] HITRAN isotopomer number for CO2 isotope 8, 17O_12C_18O
  integer,parameter::idx_12C_17O2=16 ! [idx] HITRAN isotopomer number for CO2 isotope 9, 12C_17O2
  integer,parameter::idx_13C_18O2=17 ! [idx] HITRAN isotopomer number for CO2 isotope 10, 13C_18O2
  integer,parameter::idx_18O_13C_17O=18 ! [idx] HITRAN isotopomer number for CO2 isotope 11, 18O_13C_17O
  integer,parameter::idx_16O3=19 ! [idx] HITRAN isotopomer number for O3 isotope 1, 16O3
  integer,parameter::idx_16O_16O_18O=20 ! [idx] HITRAN isotopomer number for O3 isotope 2, 16O_16O_18O
  integer,parameter::idx_16O_18O_16O=21 ! [idx] HITRAN isotopomer number for O3 isotope 3, 16O_18O_16O
  integer,parameter::idx_16O_16O_17O=22 ! [idx] HITRAN isotopomer number for O3 isotope 4, 16O_16O_17O
  integer,parameter::idx_16O_17O_16O=23 ! [idx] HITRAN isotopomer number for O3 isotope 5, 16O_17O_16O
  integer,parameter::idx_14N2_16O=24 ! [idx] HITRAN isotopomer number for N2O isotope 1, 14N2_16O
  integer,parameter::idx_14N_15N_16O=25 ! [idx] HITRAN isotopomer number for N2O isotope 2, 14N_15N_16O
  integer,parameter::idx_15N_14N_16O=26 ! [idx] HITRAN isotopomer number for N2O isotope 3, 15N_14N_16O
  integer,parameter::idx_14N2_18O=27 ! [idx] HITRAN isotopomer number for N2O isotope 4, 14N2_18O
  integer,parameter::idx_14N2_17O=28 ! [idx] HITRAN isotopomer number for N2O isotope 5, 14N2_17O
  integer,parameter::idx_12C_16O=29 ! [idx] HITRAN isotopomer number for CO isotope 1, 12C_16O
  integer,parameter::idx_13C_16O=30 ! [idx] HITRAN isotopomer number for CO isotope 2, 13C_16O
  integer,parameter::idx_12C_18O=31 ! [idx] HITRAN isotopomer number for CO isotope 3, 12C_18O
  integer,parameter::idx_12C_17O=32 ! [idx] HITRAN isotopomer number for CO isotope 4, 12C_17O
  integer,parameter::idx_13C_18O=33 ! [idx] HITRAN isotopomer number for CO isotope 5, 13C_18O
  integer,parameter::idx_13C_17O=34 ! [idx] HITRAN isotopomer number for CO isotope 6, 13C_17O
  integer,parameter::idx_12C_1H4=35 ! [idx] HITRAN isotopomer number for CH4 isotope 1, 12C_1H4
  integer,parameter::idx_13C_1H4=36 ! [idx] HITRAN isotopomer number for CH4 isotope 2, 13C_1H4
  integer,parameter::idx_12C_1H3_2H=37 ! [idx] HITRAN isotopomer number for CH4 isotope 3, 12C_1H3_2H
  integer,parameter::idx_13C_1H3_2H=38 ! [idx] HITRAN isotopomer number for CH4 isotope 4, 13C_1H3_2H
  integer,parameter::idx_16O2=39 ! [idx] HITRAN isotopomer number for O2 isotope 1, 16O2
  integer,parameter::idx_16O_18O=40 ! [idx] HITRAN isotopomer number for O2 isotope 2, 16O_18O
  integer,parameter::idx_16O_17O=41 ! [idx] HITRAN isotopomer number for O2 isotope 3, 16O_17O
  integer,parameter::idx_14N_16O=42 ! [idx] HITRAN isotopomer number for NO isotope 1, 14N_16O
  integer,parameter::idx_15N_16O=43 ! [idx] HITRAN isotopomer number for NO isotope 2, 15N_16O
  integer,parameter::idx_14N_18O=44 ! [idx] HITRAN isotopomer number for NO isotope 3, 14N_18O
  integer,parameter::idx_32S_16O2=45 ! [idx] HITRAN isotopomer number for SO2 isotope 1, 32S_16O2
  integer,parameter::idx_34S_16O2=46 ! [idx] HITRAN isotopomer number for SO2 isotope 2, 34S_16O2
  integer,parameter::idx_14N_16O2=47 ! [idx] HITRAN isotopomer number for NO2 isotope 1, 14N_16O2
  integer,parameter::idx_14N_1H3=48 ! [idx] HITRAN isotopomer number for NH3 isotope 1, 14N_1H3
  integer,parameter::idx_15N_1H3=49 ! [idx] HITRAN isotopomer number for NH3 isotope 2, 15N_1H3
  integer,parameter::idx_1H_14N_16O3=50 ! [idx] HITRAN isotopomer number for HNO3 isotope 1, 1H_14N_16O3
  integer,parameter::idx_1H_15N_16O3=51 ! [idx] HITRAN isotopomer number for HNO3 isotope 2, 1H_15N_16O3
  integer,parameter::idx_16O_1H=52 ! [idx] HITRAN isotopomer number for OH isotope 1, 16O_1H
  integer,parameter::idx_18O_1H=53 ! [idx] HITRAN isotopomer number for OH isotope 2, 18O_1H
  integer,parameter::idx_16O_2H=54 ! [idx] HITRAN isotopomer number for OH isotope 3, 16O_2H
  integer,parameter::idx_1H_19F=55 ! [idx] HITRAN isotopomer number for HF isotope 1, 1H_19F
  integer,parameter::idx_2H_19F=56 ! [idx] HITRAN isotopomer number for HF isotope 2, 2H_19F
  integer,parameter::idx_1H_35Cl=57 ! [idx] HITRAN isotopomer number for HCl isotope 1, 1H_35Cl
  integer,parameter::idx_1H_37Cl=58 ! [idx] HITRAN isotopomer number for HCl isotope 2, 1H_37Cl
  integer,parameter::idx_2H_35Cl=59 ! [idx] HITRAN isotopomer number for HCl isotope 3, 2H_35Cl
  integer,parameter::idx_2H_37Cl=60 ! [idx] HITRAN isotopomer number for HCl isotope 4, 2H_37Cl
  integer,parameter::idx_1H_79Br=61 ! [idx] HITRAN isotopomer number for HBr isotope 1, 1H_79Br
  integer,parameter::idx_1H_81Br=62 ! [idx] HITRAN isotopomer number for HBr isotope 2, 1H_81Br
  integer,parameter::idx_2H_79Br=63 ! [idx] HITRAN isotopomer number for HBr isotope 3, 2H_79Br
  integer,parameter::idx_2H_81Br=64 ! [idx] HITRAN isotopomer number for HBr isotope 4, 2H_81Br
  integer,parameter::idx_1H_127I=65 ! [idx] HITRAN isotopomer number for HI isotope 1, 1H_127I
  integer,parameter::idx_2H_127I=66 ! [idx] HITRAN isotopomer number for HI isotope 2, 2H_127I
  integer,parameter::idx_35Cl_16O=67 ! [idx] HITRAN isotopomer number for ClO isotope 1, 35Cl_16O
  integer,parameter::idx_37Cl_16O=68 ! [idx] HITRAN isotopomer number for ClO isotope 2, 37Cl_16O
  integer,parameter::idx_16O_12C_32S=69 ! [idx] HITRAN isotopomer number for OCS isotope 1, 16O_12C_32S
  integer,parameter::idx_16O_12C_34S=70 ! [idx] HITRAN isotopomer number for OCS isotope 2, 16O_12C_34S
  integer,parameter::idx_16O_13C_32S=71 ! [idx] HITRAN isotopomer number for OCS isotope 3, 16O_13C_32S
  integer,parameter::idx_16O_12C_33S=72 ! [idx] HITRAN isotopomer number for OCS isotope 4, 16O_12C_33S
  integer,parameter::idx_18O_12C_32S=73 ! [idx] HITRAN isotopomer number for OCS isotope 5, 18O_12C_32S
  integer,parameter::idx_1H2_12C_16O=74 ! [idx] HITRAN isotopomer number for H2CO isotope 1, 1H2_12C_16O
  integer,parameter::idx_1H2_13C_16O=75 ! [idx] HITRAN isotopomer number for H2CO isotope 2, 1H2_13C_16O
  integer,parameter::idx_1H2_12C_18O=76 ! [idx] HITRAN isotopomer number for H2CO isotope 3, 1H2_12C_18O
  integer,parameter::idx_1H_16O_35Cl=77 ! [idx] HITRAN isotopomer number for HOCl isotope 1, 1H_16O_35Cl
  integer,parameter::idx_1H_16O_37Cl=78 ! [idx] HITRAN isotopomer number for HOCl isotope 2, 1H_16O_37Cl
  integer,parameter::idx_14N2=79 ! [idx] HITRAN isotopomer number for N2 isotope 1, 14N2
  integer,parameter::idx_14N_15N=80 ! [idx] HITRAN isotopomer number for N2 isotope 2, 14N_15N
  integer,parameter::idx_1H_12C_14N=81 ! [idx] HITRAN isotopomer number for HCN isotope 1, 1H_12C_14N
  integer,parameter::idx_1H_13C_14N=82 ! [idx] HITRAN isotopomer number for HCN isotope 2, 1H_13C_14N
  integer,parameter::idx_1H_12C_15N=83 ! [idx] HITRAN isotopomer number for HCN isotope 3, 1H_12C_15N
  integer,parameter::idx_12C_1H_35Cl=84 ! [idx] HITRAN isotopomer number for CH3Cl isotope 1, 12C_1H_35Cl
  integer,parameter::idx_12C_1H_37Cl=85 ! [idx] HITRAN isotopomer number for CH3Cl isotope 2, 12C_1H_37Cl
  integer,parameter::idx_1H2_16O2=86 ! [idx] HITRAN isotopomer number for H2O2 isotope 1, 1H2_16O2
  integer,parameter::idx_12C2_1H2=87 ! [idx] HITRAN isotopomer number for C2H2 isotope 1, 12C2_1H2
  integer,parameter::idx_1H_12C_13C_1H=88 ! [idx] HITRAN isotopomer number for C2H2 isotope 2, 1H_12C_13C_1H
  integer,parameter::idx_1H_12C_12C_2H=89 ! [idx] HITRAN isotopomer number for C2H2 isotope 3, 1H_12C_12C_2H
  integer,parameter::idx_12C2_1H6=90 ! [idx] HITRAN isotopomer number for C2H6 isotope 1, 12C2_1H6
  integer,parameter::idx_12C_13C_1H6=91 ! [idx] HITRAN isotopomer number for C2H6 isotope 2, 12C_13C_1H6
  integer,parameter::idx_31P_1H3=92 ! [idx] HITRAN isotopomer number for PH3 isotope 1, 31P_1H3
  integer,parameter::idx_12C_16O_19F2=93 ! [idx] HITRAN isotopomer number for COF2 isotope 1, 12C_16O_19F2
  integer,parameter::idx_13C_16O_19F2=94 ! [idx] HITRAN isotopomer number for COF2 isotope 2, 13C_16O_19F2
  integer,parameter::idx_32S_19F6=95 ! [idx] HITRAN isotopomer number for SF6 isotope 1, 32S_19F6
  integer,parameter::idx_1H2_32S=96 ! [idx] HITRAN isotopomer number for H2S isotope 1, 1H2_32S
  integer,parameter::idx_1H_34S_1H=97 ! [idx] HITRAN isotopomer number for H2S isotope 2, 1H_34S_1H
  integer,parameter::idx_1H_33S_1H=98 ! [idx] HITRAN isotopomer number for H2S isotope 3, 1H_33S_1H
  integer,parameter::idx_1H2_12C_16O2=99 ! [idx] HITRAN isotopomer number for HCOOH isotope 1, 1H2_12C_16O2
  integer,parameter::idx_1H_16O2=100 ! [idx] HITRAN isotopomer number for HO2 isotope 1, 1H_16O2
  integer,parameter::idx_16O=101 ! [idx] HITRAN isotopomer number for O isotope 1, 16O
  integer,parameter::idx_35Cl_16O_14N_16O2=102 ! [idx] HITRAN isotopomer number for ClONO2 isotope 1, 35Cl_16O_14N_16O2
  integer,parameter::idx_37Cl_16O_14N_16O2=103 ! [idx] HITRAN isotopomer number for ClONO2 isotope 2, 37Cl_16O_14N_16O2
  integer,parameter::idx_14N_16O_ion=104 ! [idx] HITRAN isotopomer number for NO+ isotope 1, 14N_16O+
  integer,parameter::idx_1H_16O_79Br=105 ! [idx] HITRAN isotopomer number for HOBr isotope 1, 1H_16O_79Br
  integer,parameter::idx_1H_16O_81Br=106 ! [idx] HITRAN isotopomer number for HOBr isotope 2, 1H_16O_81Br
  integer,parameter::idx_12C2_1H4=107 ! [idx] HITRAN isotopomer number for C2H4 isotope 1, 12C2_1H4
  integer,parameter::idx_12C_13C_1H4=108 ! [idx] HITRAN isotopomer number for C2H4 isotope 2, 12C_13C_1H4
  integer,parameter::idx_12C2_1H3_16O_1H=109 ! [idx] HITRAN isotopomer number for CH3OH isotope 1, 12C2_1H3_16O_1H
  integer,parameter::idx_12C_1H3_79Br=110 ! [idx] HITRAN isotopomer number for CH3Br isotope 1, 12C_1H3_79Br
  integer,parameter::idx_12C_1H3_81Br=111 ! [idx] HITRAN isotopomer number for CH3Br isotope 2, 12C_1H3_81Br
  integer,parameter::idx_12C2_1H3_14N=112 ! [idx] HITRAN isotopomer number for CH3CN isotope 1, 12C2_1H3_14N
  integer,parameter::idx_12C_F4=113 ! [idx] HITRAN isotopomer number for CF4 isotope 1, 12C_F4
  integer,parameter::idx_12C4_1H2=114 ! [idx] HITRAN isotopomer number for C4H2 isotope 1, 12C4_1H2
  integer,parameter::idx_1H_12C3_14N=115 ! [idx] HITRAN isotopomer number for HC3N isotope 1, 1H_12C3_14N
  integer,parameter::idx_1H=116 ! [idx] HITRAN isotopomer number for H2 isotope 1, 1H
  integer,parameter::idx_2H=117 ! [idx] HITRAN isotopomer number for H2 isotope 2, 2H
  integer,parameter::idx_12C_32S=118 ! [idx] HITRAN isotopomer number for CS isotope 1, 12C_32S
  integer,parameter::idx_13C_32S=119 ! [idx] HITRAN isotopomer number for CS isotope 2, 13C_32S
  integer,parameter::idx_12C_34S=120 ! [idx] HITRAN isotopomer number for CS isotope 3, 12C_34S
  integer,parameter::idx_13C_34S=121 ! [idx] HITRAN isotopomer number for CS isotope 4, 13C_34S
  integer,parameter::idx_32S_16O3=122 ! [idx] HITRAN isotopomer number for SO3 isotope 1, 32S_16O3
  integer,parameter::idx_12C2_14N2=123 ! [idx] HITRAN isotopomer number for C2N2 isotope 1, 12C2_14N2
  integer,parameter::idx_12C_16O_35Cl2=124 ! [idx] HITRAN isotopomer number for COCl2 isotope 1, 12C_16O_35Cl2
  integer,parameter::idx_12C_16O_35Cl_37Cl=125 ! [idx] HITRAN isotopomer number for COCl2 isotope 2, 12C_16O_35Cl_37Cl

contains

subroutine rtl_fnc_tpt_xpn_get(xpn)

! Purpose: Fills array with exponent which defines
! temperature dependence of rotational partition function
! of each HITRAN molecule

! use htrn_cst,only:mlc_nbr_max_htrn ! [mdl] HITRAN constants, subroutines
  implicit none
! Output
  real,intent(out)::xpn(mlc_nbr_max_htrn) ! [frc] Exponent defining temperature dependence of rotational partition function

  xpn(idx_H2O)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_CO2)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_O3)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_N2O)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_CO)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_CH4)=1.5 ! [frc] Group 3, Spherical Rotors
  xpn(idx_O2)=1.0 ! [frc] Group 5, Triplet Ground Electronic States 
  xpn(idx_NO)=1.0 ! [frc] Group 6, Doublet Ground Electronic States (Half Integer J)
  xpn(idx_SO2)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_NO2)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_NH3)=1.5 ! [frc] Group 4, Symmetric Rotors
  xpn(idx_HNO3)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_OH)=1.0 ! [frc] Group 6, Doublet Ground Electronic States (Half Integer J)
  xpn(idx_HF)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_HCl)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_HBr)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_HI)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_ClO)=1.0 ! [frc] Group 6, Doublet Ground Electronic States (Half Integer J)
  xpn(idx_OCS)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_H2CO)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_HOCl)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_N2)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_HCN)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_CH3Cl)=1.5 ! [frc] Group 4, Symmetric Rotors
  xpn(idx_H2O2)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_C2H2)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_C2H6)=1.5 ! [frc] Group 4, Symmetric Rotors
  xpn(idx_PH3)=1.5 ! [frc] Group 4, Symmetric Rotors
  xpn(idx_COF2)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_SF6)=1.5 ! [frc] Group 4, Symmetric Rotors
  xpn(idx_H2S)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_HCOOH)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_HO2)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_O)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_ClONO2)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_NO_ion)=1.0 ! [frc] Group 2, Diatomic and Linear Molecules with Integer J
  xpn(idx_HOBr)=1.5 ! [frc] Group 1, Asymmetric Rotors
  xpn(idx_C2H4)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_CH3OH)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_CH3Br)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_CH3CN)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_CF4)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_C4H2)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_HC3N)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_H2)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_CS)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_SO3)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_C2N2)=1.5 ! [frc] Group 0, Unknown group
  xpn(idx_COCl2)=1.5 ! [frc] Group 0, Unknown group
  return
end subroutine rtl_fnc_tpt_xpn_get

subroutine mmw_mlc_get(mmw)

! Purpose: Fills an array containing the mean molecular weight
! for each HITRAN molecule

! use htrn_cst,only:mlc_nbr_max_htrn ! [mdl] HITRAN constants, subroutines
  implicit none
! Output
  real,intent(out)::mmw(mlc_nbr_max_htrn) ! [kg mol-1] mean molecular weight of all HITRAN molecules

! Define mean molecular weight in SI units instead of g mol-1
! This keeps Avagadro's number fixed and gets rid of many factors of 1000.0

  mmw(idx_H2O)=1.8015261e-02 ! [kg mol-1] mmw of H2O
  mmw(idx_CO2)=4.4009743e-02 ! [kg mol-1] mmw of CO2
  mmw(idx_O3)=4.7997832e-02 ! [kg mol-1] mmw of O3
  mmw(idx_N2O)=4.4012674e-02 ! [kg mol-1] mmw of N2O
  mmw(idx_CO)=2.8010445e-02 ! [kg mol-1] mmw of CO
  mmw(idx_CH4)=1.6043074e-02 ! [kg mol-1] mmw of CH4
  mmw(idx_O2)=3.1998575e-02 ! [kg mol-1] mmw of O2
  mmw(idx_NO)=3.0005630e-02 ! [kg mol-1] mmw of NO
  mmw(idx_SO2)=6.4046674e-02 ! [kg mol-1] mmw of SO2
  mmw(idx_NO2)=4.5992904e-02 ! [kg mol-1] mmw of NO2
  mmw(idx_NH3)=1.7030201e-02 ! [kg mol-1] mmw of NH3
  mmw(idx_HNO3)=6.2999296e-02 ! [kg mol-1] mmw of HNO3
  mmw(idx_OH)=1.7006907e-02 ! [kg mol-1] mmw of OH
  mmw(idx_HF)=2.0006386e-02 ! [kg mol-1] mmw of HF
  mmw(idx_HCl)=3.6460710e-02 ! [kg mol-1] mmw of HCl
  mmw(idx_HBr)=8.0911588e-02 ! [kg mol-1] mmw of HBr
  mmw(idx_HI)=1.2791245e-01 ! [kg mol-1] mmw of HI
  mmw(idx_ClO)=5.1447643e-02 ! [kg mol-1] mmw of ClO
  mmw(idx_OCS)=6.0071832e-02 ! [kg mol-1] mmw of OCS
  mmw(idx_H2CO)=3.0025657e-02 ! [kg mol-1] mmw of H2CO
  mmw(idx_HOCl)=5.2455469e-02 ! [kg mol-1] mmw of HOCl
  mmw(idx_N2)=2.8013603e-02 ! [kg mol-1] mmw of N2
  mmw(idx_HCN)=2.7025618e-02 ! [kg mol-1] mmw of HCN
  mmw(idx_CH3Cl)=5.0476203e-02 ! [kg mol-1] mmw of CH3Cl
  mmw(idx_H2O2)=3.4005480e-02 ! [kg mol-1] mmw of H2O2
  mmw(idx_C2H2)=2.6037999e-02 ! [kg mol-1] mmw of C2H2
  mmw(idx_C2H6)=3.0069000e-02 ! [kg mol-1] mmw of C2H6
  mmw(idx_PH3)=3.3997238e-02 ! [kg mol-1] mmw of PH3
  mmw(idx_COF2)=6.6002869e-02 ! [kg mol-1] mmw of COF2
  mmw(idx_SF6)=1.4596249e-01 ! [kg mol-1] mmw of SF6
  mmw(idx_H2S)=3.4079355e-02 ! [kg mol-1] mmw of H2S
  mmw(idx_HCOOH)=4.6005480e-02 ! [kg mol-1] mmw of HCOOH
  mmw(idx_HO2)=3.2997655e-02 ! [kg mol-1] mmw of HO2
  mmw(idx_O)=1.5994915e-02 ! [kg mol-1] mmw of O
  mmw(idx_ClONO2)=9.7440548e-02 ! [kg mol-1] mmw of ClONO2
  mmw(idx_NO_ion)=2.9997989e-02 ! [kg mol-1] mmw of NO+
  mmw(idx_HOBr)=9.6906346e-02 ! [kg mol-1] mmw of HOBr
  mmw(idx_C2H4)=2.8053350e-02 ! [kg mol-1] mmw of C2H4
  mmw(idx_CH3OH)=3.2026215e-02 ! [kg mol-1] mmw of CH3OH
  mmw(idx_CH3Br)=9.4927081e-02 ! [kg mol-1] mmw of CH3Br
  mmw(idx_CH3CN)=4.1026549e-02 ! [kg mol-1] mmw of CH3CN
  mmw(idx_CF4)=8.7993616e-02 ! [kg mol-1] mmw of CF4
  mmw(idx_C4H2)=5.0015650e-02 ! [kg mol-1] mmw of C4H2
  mmw(idx_HC3N)=5.1010899e-02 ! [kg mol-1] mmw of HC3N
  mmw(idx_H2)=2.0159634e-03 ! [kg mol-1] mmw of H2
  mmw(idx_CS)=4.4072299e-02 ! [kg mol-1] mmw of CS
  mmw(idx_SO3)=7.9956820e-02 ! [kg mol-1] mmw of SO3
  mmw(idx_C2N2)=5.2006148e-02 ! [kg mol-1] mmw of C2N2
  mmw(idx_COCl2)=9.8711621e-02 ! [kg mol-1] mmw of COCl2
  return
end subroutine mmw_mlc_get

subroutine mmw_iso_get(mmw)

! Purpose: Fills array with mean molecular weight
! of each HITRAN isotope

! use htrn_cst,only:iso_nbr_max_htrn ! [mdl] HITRAN constants, subroutines
  implicit none
! Output
  real,intent(out)::mmw(iso_nbr_max_htrn) ! [kg mol-1] mean molecular weight of all HITRAN isotopomers

! Define mean molecular weight in SI units instead of g mol-1
! This keeps Avagadro's number fixed and gets rid of many factors of 1000.0

  mmw(idx_1H2_16O)=1.8010565e-02 ! [kg mol-1] mmw of 1H2_16O
  mmw(idx_1H2_18O)=2.0014811e-02 ! [kg mol-1] mmw of 1H2_18O
  mmw(idx_1H2_17O)=1.9014780e-02 ! [kg mol-1] mmw of 1H2_17O
  mmw(idx_1H_2H_16O)=1.9016740e-02 ! [kg mol-1] mmw of 1H_2H_16O
  mmw(idx_1H_2H_18O)=2.1020985e-02 ! [kg mol-1] mmw of 1H_2H_18O
  mmw(idx_1H_2H_17O)=2.0020956e-02 ! [kg mol-1] mmw of 1H_2H_17O
  mmw(idx_2H_2H_16O)=2.0022915e-02 ! [kg mol-1] mmw of 2H_2H_16O
  mmw(idx_12C_16O2)=4.3989830e-02 ! [kg mol-1] mmw of 12C_16O2
  mmw(idx_13C_16O2)=4.4993185e-02 ! [kg mol-1] mmw of 13C_16O2
  mmw(idx_16O_12C_18O)=4.5994076e-02 ! [kg mol-1] mmw of 16O_12C_18O
  mmw(idx_16O_12C_17O)=4.4994045e-02 ! [kg mol-1] mmw of 16O_12C_17O
  mmw(idx_16O_13C_18O)=4.6997431e-02 ! [kg mol-1] mmw of 16O_13C_18O
  mmw(idx_16O_13C_17O)=4.5997400e-02 ! [kg mol-1] mmw of 16O_13C_17O
  mmw(idx_12C_18O2)=4.7998322e-02 ! [kg mol-1] mmw of 12C_18O2
  mmw(idx_17O_12C_18O)=4.6998291e-02 ! [kg mol-1] mmw of 17O_12C_18O
  mmw(idx_12C_17O2)=4.5998262e-02 ! [kg mol-1] mmw of 12C_17O2
  mmw(idx_13C_18O2)=4.9001675e-02 ! [kg mol-1] mmw of 13C_18O2
  mmw(idx_18O_13C_17O)=4.8001646e-02 ! [kg mol-1] mmw of 18O_13C_17O
  mmw(idx_16O3)=4.7984745e-02 ! [kg mol-1] mmw of 16O3
  mmw(idx_16O_16O_18O)=4.9988991e-02 ! [kg mol-1] mmw of 16O_16O_18O
  mmw(idx_16O_18O_16O)=4.9988991e-02 ! [kg mol-1] mmw of 16O_18O_16O
  mmw(idx_16O_16O_17O)=4.8988960e-02 ! [kg mol-1] mmw of 16O_16O_17O
  mmw(idx_16O_17O_16O)=4.8988960e-02 ! [kg mol-1] mmw of 16O_17O_16O
  mmw(idx_14N2_16O)=4.4001062e-02 ! [kg mol-1] mmw of 14N2_16O
  mmw(idx_14N_15N_16O)=4.4998096e-02 ! [kg mol-1] mmw of 14N_15N_16O
  mmw(idx_15N_14N_16O)=4.4998096e-02 ! [kg mol-1] mmw of 15N_14N_16O
  mmw(idx_14N2_18O)=4.6005308e-02 ! [kg mol-1] mmw of 14N2_18O
  mmw(idx_14N2_17O)=4.5005278e-02 ! [kg mol-1] mmw of 14N2_17O
  mmw(idx_12C_16O)=2.7994915e-02 ! [kg mol-1] mmw of 12C_16O
  mmw(idx_13C_16O)=2.8998270e-02 ! [kg mol-1] mmw of 13C_16O
  mmw(idx_12C_18O)=2.9999161e-02 ! [kg mol-1] mmw of 12C_18O
  mmw(idx_12C_17O)=2.8999130e-02 ! [kg mol-1] mmw of 12C_17O
  mmw(idx_13C_18O)=3.1002516e-02 ! [kg mol-1] mmw of 13C_18O
  mmw(idx_13C_17O)=3.0002485e-02 ! [kg mol-1] mmw of 13C_17O
  mmw(idx_12C_1H4)=1.6031300e-02 ! [kg mol-1] mmw of 12C_1H4
  mmw(idx_13C_1H4)=1.7034655e-02 ! [kg mol-1] mmw of 13C_1H4
  mmw(idx_12C_1H3_2H)=1.7037475e-02 ! [kg mol-1] mmw of 12C_1H3_2H
  mmw(idx_13C_1H3_2H)=1.8040830e-02 ! [kg mol-1] mmw of 13C_1H3_2H
  mmw(idx_16O2)=3.1989830e-02 ! [kg mol-1] mmw of 16O2
  mmw(idx_16O_18O)=3.3994076e-02 ! [kg mol-1] mmw of 16O_18O
  mmw(idx_16O_17O)=3.2994045e-02 ! [kg mol-1] mmw of 16O_17O
  mmw(idx_14N_16O)=2.9997989e-02 ! [kg mol-1] mmw of 14N_16O
  mmw(idx_15N_16O)=3.0995023e-02 ! [kg mol-1] mmw of 15N_16O
  mmw(idx_14N_18O)=3.2002234e-02 ! [kg mol-1] mmw of 14N_18O
  mmw(idx_32S_16O2)=6.3961901e-02 ! [kg mol-1] mmw of 32S_16O2
  mmw(idx_34S_16O2)=6.5957695e-02 ! [kg mol-1] mmw of 34S_16O2
  mmw(idx_14N_16O2)=4.5992904e-02 ! [kg mol-1] mmw of 14N_16O2
  mmw(idx_14N_1H3)=1.7026549e-02 ! [kg mol-1] mmw of 14N_1H3
  mmw(idx_15N_1H3)=1.8023583e-02 ! [kg mol-1] mmw of 15N_1H3
  mmw(idx_1H_14N_16O3)=6.2995644e-02 ! [kg mol-1] mmw of 1H_14N_16O3
  mmw(idx_1H_15N_16O3)=6.3992680e-02 ! [kg mol-1] mmw of 1H_15N_16O3
  mmw(idx_16O_1H)=1.7002740e-02 ! [kg mol-1] mmw of 16O_1H
  mmw(idx_18O_1H)=1.9006986e-02 ! [kg mol-1] mmw of 18O_1H
  mmw(idx_16O_2H)=1.8008915e-02 ! [kg mol-1] mmw of 16O_2H
  mmw(idx_1H_19F)=2.0006229e-02 ! [kg mol-1] mmw of 1H_19F
  mmw(idx_2H_19F)=2.1012404e-02 ! [kg mol-1] mmw of 2H_19F
  mmw(idx_1H_35Cl)=3.5976678e-02 ! [kg mol-1] mmw of 1H_35Cl
  mmw(idx_1H_37Cl)=3.7973729e-02 ! [kg mol-1] mmw of 1H_37Cl
  mmw(idx_2H_35Cl)=3.6982853e-02 ! [kg mol-1] mmw of 2H_35Cl
  mmw(idx_2H_37Cl)=3.8979904e-02 ! [kg mol-1] mmw of 2H_37Cl
  mmw(idx_1H_79Br)=7.9926160e-02 ! [kg mol-1] mmw of 1H_79Br
  mmw(idx_1H_81Br)=8.1924115e-02 ! [kg mol-1] mmw of 1H_81Br
  mmw(idx_2H_79Br)=8.0932336e-02 ! [kg mol-1] mmw of 2H_79Br
  mmw(idx_2H_81Br)=8.2930289e-02 ! [kg mol-1] mmw of 2H_81Br
  mmw(idx_1H_127I)=1.2791230e-01 ! [kg mol-1] mmw of 1H_127I
  mmw(idx_2H_127I)=1.2891847e-01 ! [kg mol-1] mmw of 2H_127I
  mmw(idx_35Cl_16O)=5.0963768e-02 ! [kg mol-1] mmw of 35Cl_16O
  mmw(idx_37Cl_16O)=5.2960819e-02 ! [kg mol-1] mmw of 37Cl_16O
  mmw(idx_16O_12C_32S)=5.9966986e-02 ! [kg mol-1] mmw of 16O_12C_32S
  mmw(idx_16O_12C_34S)=6.1962780e-02 ! [kg mol-1] mmw of 16O_12C_34S
  mmw(idx_16O_13C_32S)=6.0970341e-02 ! [kg mol-1] mmw of 16O_13C_32S
  mmw(idx_16O_12C_33S)=6.0966371e-02 ! [kg mol-1] mmw of 16O_12C_33S
  mmw(idx_18O_12C_32S)=6.1971231e-02 ! [kg mol-1] mmw of 18O_12C_32S
  mmw(idx_1H2_12C_16O)=3.0010565e-02 ! [kg mol-1] mmw of 1H2_12C_16O
  mmw(idx_1H2_13C_16O)=3.1013920e-02 ! [kg mol-1] mmw of 1H2_13C_16O
  mmw(idx_1H2_12C_18O)=3.2014811e-02 ! [kg mol-1] mmw of 1H2_12C_18O
  mmw(idx_1H_16O_35Cl)=5.1971593e-02 ! [kg mol-1] mmw of 1H_16O_35Cl
  mmw(idx_1H_16O_37Cl)=5.3968644e-02 ! [kg mol-1] mmw of 1H_16O_37Cl
  mmw(idx_14N2)=2.8006148e-02 ! [kg mol-1] mmw of 14N2
  mmw(idx_14N_15N)=2.9003182e-02 ! [kg mol-1] mmw of 14N_15N
  mmw(idx_1H_12C_14N)=2.7010899e-02 ! [kg mol-1] mmw of 1H_12C_14N
  mmw(idx_1H_13C_14N)=2.8014254e-02 ! [kg mol-1] mmw of 1H_13C_14N
  mmw(idx_1H_12C_15N)=2.8007933e-02 ! [kg mol-1] mmw of 1H_12C_15N
  mmw(idx_12C_1H_35Cl)=4.9992328e-02 ! [kg mol-1] mmw of 12C_1H_35Cl
  mmw(idx_12C_1H_37Cl)=5.1989379e-02 ! [kg mol-1] mmw of 12C_1H_37Cl
  mmw(idx_1H2_16O2)=3.4005480e-02 ! [kg mol-1] mmw of 1H2_16O2
  mmw(idx_12C2_1H2)=2.6015650e-02 ! [kg mol-1] mmw of 12C2_1H2
  mmw(idx_1H_12C_13C_1H)=2.7019005e-02 ! [kg mol-1] mmw of 1H_12C_13C_1H
  mmw(idx_1H_12C_12C_2H)=2.7021825e-02 ! [kg mol-1] mmw of 1H_12C_12C_2H
  mmw(idx_12C2_1H6)=3.0046950e-02 ! [kg mol-1] mmw of 12C2_1H6
  mmw(idx_12C_13C_1H6)=3.1050305e-02 ! [kg mol-1] mmw of 12C_13C_1H6
  mmw(idx_31P_1H3)=3.3997238e-02 ! [kg mol-1] mmw of 31P_1H3
  mmw(idx_12C_16O_19F2)=6.5991722e-02 ! [kg mol-1] mmw of 12C_16O_19F2
  mmw(idx_13C_16O_19F2)=6.6995083e-02 ! [kg mol-1] mmw of 13C_16O_19F2
  mmw(idx_32S_19F6)=1.4596249e-01 ! [kg mol-1] mmw of 32S_19F6
  mmw(idx_1H2_32S)=3.3987721e-02 ! [kg mol-1] mmw of 1H2_32S
  mmw(idx_1H_34S_1H)=3.5983515e-02 ! [kg mol-1] mmw of 1H_34S_1H
  mmw(idx_1H_33S_1H)=3.4987105e-02 ! [kg mol-1] mmw of 1H_33S_1H
  mmw(idx_1H2_12C_16O2)=4.6005480e-02 ! [kg mol-1] mmw of 1H2_12C_16O2
  mmw(idx_1H_16O2)=3.2997655e-02 ! [kg mol-1] mmw of 1H_16O2
  mmw(idx_16O)=1.5994915e-02 ! [kg mol-1] mmw of 16O
  mmw(idx_35Cl_16O_14N_16O2)=9.6956672e-02 ! [kg mol-1] mmw of 35Cl_16O_14N_16O2
  mmw(idx_37Cl_16O_14N_16O2)=9.8953723e-02 ! [kg mol-1] mmw of 37Cl_16O_14N_16O2
  mmw(idx_14N_16O_ion)=2.9997989e-02 ! [kg mol-1] mmw of 14N_16O+
  mmw(idx_1H_16O_79Br)=9.5921076e-02 ! [kg mol-1] mmw of 1H_16O_79Br
  mmw(idx_1H_16O_81Br)=9.7919027e-02 ! [kg mol-1] mmw of 1H_16O_81Br
  mmw(idx_12C2_1H4)=2.8031300e-02 ! [kg mol-1] mmw of 12C2_1H4
  mmw(idx_12C_13C_1H4)=2.9034655e-02 ! [kg mol-1] mmw of 12C_13C_1H4
  mmw(idx_12C2_1H3_16O_1H)=3.2026215e-02 ! [kg mol-1] mmw of 12C2_1H3_16O_1H
  mmw(idx_12C_1H3_79Br)=9.3941811e-02 ! [kg mol-1] mmw of 12C_1H3_79Br
  mmw(idx_12C_1H3_81Br)=9.5939764e-02 ! [kg mol-1] mmw of 12C_1H3_81Br
  mmw(idx_12C2_1H3_14N)=4.1026549e-02 ! [kg mol-1] mmw of 12C2_1H3_14N
  mmw(idx_12C_F4)=8.7993616e-02 ! [kg mol-1] mmw of 12C_F4
  mmw(idx_12C4_1H2)=5.0015650e-02 ! [kg mol-1] mmw of 12C4_1H2
  mmw(idx_1H_12C3_14N)=5.1010899e-02 ! [kg mol-1] mmw of 1H_12C3_14N
  mmw(idx_1H)=2.0156500e-03 ! [kg mol-1] mmw of 1H
  mmw(idx_2H)=3.0218250e-03 ! [kg mol-1] mmw of 2H
  mmw(idx_12C_32S)=4.3971036e-02 ! [kg mol-1] mmw of 12C_32S
  mmw(idx_13C_32S)=4.5966787e-02 ! [kg mol-1] mmw of 13C_32S
  mmw(idx_12C_34S)=4.4974368e-02 ! [kg mol-1] mmw of 12C_34S
  mmw(idx_13C_34S)=4.4970399e-02 ! [kg mol-1] mmw of 13C_34S
  mmw(idx_32S_16O3)=7.9956820e-02 ! [kg mol-1] mmw of 32S_16O3
  mmw(idx_12C2_14N2)=5.2006148e-02 ! [kg mol-1] mmw of 12C2_14N2
  mmw(idx_12C_16O_35Cl2)=9.7932620e-02 ! [kg mol-1] mmw of 12C_16O_35Cl2
  mmw(idx_12C_16O_35Cl_37Cl)=9.9929670e-02 ! [kg mol-1] mmw of 12C_16O_35Cl_37Cl
  return
end subroutine mmw_iso_get

subroutine iso_idx_map_get(map)

! Purpose: Fills array which maps molecular and isotopic indices to isotopomer index

! use htrn_cst,only:iso_nbr_max_htrn ! [mdl] HITRAN constants, subroutines
  implicit none
! Output args
  integer,intent(out)::map(iso_per_mlc_nbr_max_htrn,mlc_nbr_max_htrn) ! [idx] Map of mlc,iso indices to isotopomer index

! Initialize map
  map(:,:)=0
! Fill in map for all valid isotopomers

! Molecule 1, H2O
  map(1,1)=1 ! [idx] 1H2_16O
  map(2,1)=2 ! [idx] 1H2_18O
  map(3,1)=3 ! [idx] 1H2_17O
  map(4,1)=4 ! [idx] 1H_2H_16O
  map(5,1)=5 ! [idx] 1H_2H_18O
  map(6,1)=6 ! [idx] 1H_2H_17O
  map(7,1)=7 ! [idx] 2H_2H_16O

! Molecule 2, CO2
  map(1,2)=8 ! [idx] 12C_16O2
  map(2,2)=9 ! [idx] 13C_16O2
  map(3,2)=10 ! [idx] 16O_12C_18O
  map(4,2)=11 ! [idx] 16O_12C_17O
  map(5,2)=12 ! [idx] 16O_13C_18O
  map(6,2)=13 ! [idx] 16O_13C_17O
  map(7,2)=14 ! [idx] 12C_18O2
  map(8,2)=15 ! [idx] 17O_12C_18O
  map(9,2)=16 ! [idx] 12C_17O2
  map(10,2)=17 ! [idx] 13C_18O2
  map(11,2)=18 ! [idx] 18O_13C_17O

! Molecule 3, O3
  map(1,3)=19 ! [idx] 16O3
  map(2,3)=20 ! [idx] 16O_16O_18O
  map(3,3)=21 ! [idx] 16O_18O_16O
  map(4,3)=22 ! [idx] 16O_16O_17O
  map(5,3)=23 ! [idx] 16O_17O_16O

! Molecule 4, N2O
  map(1,4)=24 ! [idx] 14N2_16O
  map(2,4)=25 ! [idx] 14N_15N_16O
  map(3,4)=26 ! [idx] 15N_14N_16O
  map(4,4)=27 ! [idx] 14N2_18O
  map(5,4)=28 ! [idx] 14N2_17O

! Molecule 5, CO
  map(1,5)=29 ! [idx] 12C_16O
  map(2,5)=30 ! [idx] 13C_16O
  map(3,5)=31 ! [idx] 12C_18O
  map(4,5)=32 ! [idx] 12C_17O
  map(5,5)=33 ! [idx] 13C_18O
  map(6,5)=34 ! [idx] 13C_17O

! Molecule 6, CH4
  map(1,6)=35 ! [idx] 12C_1H4
  map(2,6)=36 ! [idx] 13C_1H4
  map(3,6)=37 ! [idx] 12C_1H3_2H
  map(4,6)=38 ! [idx] 13C_1H3_2H

! Molecule 7, O2
  map(1,7)=39 ! [idx] 16O2
  map(2,7)=40 ! [idx] 16O_18O
  map(3,7)=41 ! [idx] 16O_17O

! Molecule 8, NO
  map(1,8)=42 ! [idx] 14N_16O
  map(2,8)=43 ! [idx] 15N_16O
  map(3,8)=44 ! [idx] 14N_18O

! Molecule 9, SO2
  map(1,9)=45 ! [idx] 32S_16O2
  map(2,9)=46 ! [idx] 34S_16O2

! Molecule 10, NO2
  map(1,10)=47 ! [idx] 14N_16O2

! Molecule 11, NH3
  map(1,11)=48 ! [idx] 14N_1H3
  map(2,11)=49 ! [idx] 15N_1H3

! Molecule 12, HNO3
  map(1,12)=50 ! [idx] 1H_14N_16O3
  map(2,12)=51 ! [idx] 1H_15N_16O3

! Molecule 13, OH
  map(1,13)=52 ! [idx] 16O_1H
  map(2,13)=53 ! [idx] 18O_1H
  map(3,13)=54 ! [idx] 16O_2H

! Molecule 14, HF
  map(1,14)=55 ! [idx] 1H_19F
  map(2,14)=56 ! [idx] 2H_19F

! Molecule 15, HCl
  map(1,15)=57 ! [idx] 1H_35Cl
  map(2,15)=58 ! [idx] 1H_37Cl
  map(3,15)=59 ! [idx] 2H_35Cl
  map(4,15)=60 ! [idx] 2H_37Cl

! Molecule 16, HBr
  map(1,16)=61 ! [idx] 1H_79Br
  map(2,16)=62 ! [idx] 1H_81Br
  map(3,16)=63 ! [idx] 2H_79Br
  map(4,16)=64 ! [idx] 2H_81Br

! Molecule 17, HI
  map(1,17)=65 ! [idx] 1H_127I
  map(2,17)=66 ! [idx] 2H_127I

! Molecule 18, ClO
  map(1,18)=67 ! [idx] 35Cl_16O
  map(2,18)=68 ! [idx] 37Cl_16O

! Molecule 19, OCS
  map(1,19)=69 ! [idx] 16O_12C_32S
  map(2,19)=70 ! [idx] 16O_12C_34S
  map(3,19)=71 ! [idx] 16O_13C_32S
  map(4,19)=72 ! [idx] 16O_12C_33S
  map(5,19)=73 ! [idx] 18O_12C_32S

! Molecule 20, H2CO
  map(1,20)=74 ! [idx] 1H2_12C_16O
  map(2,20)=75 ! [idx] 1H2_13C_16O
  map(3,20)=76 ! [idx] 1H2_12C_18O

! Molecule 21, HOCl
  map(1,21)=77 ! [idx] 1H_16O_35Cl
  map(2,21)=78 ! [idx] 1H_16O_37Cl

! Molecule 22, N2
  map(1,22)=79 ! [idx] 14N2
  map(2,22)=80 ! [idx] 14N_15N

! Molecule 23, HCN
  map(1,23)=81 ! [idx] 1H_12C_14N
  map(2,23)=82 ! [idx] 1H_13C_14N
  map(3,23)=83 ! [idx] 1H_12C_15N

! Molecule 24, CH3Cl
  map(1,24)=84 ! [idx] 12C_1H_35Cl
  map(2,24)=85 ! [idx] 12C_1H_37Cl

! Molecule 25, H2O2
  map(1,25)=86 ! [idx] 1H2_16O2

! Molecule 26, C2H2
  map(1,26)=87 ! [idx] 12C2_1H2
  map(2,26)=88 ! [idx] 1H_12C_13C_1H
  map(3,26)=89 ! [idx] 1H_12C_12C_2H

! Molecule 27, C2H6
  map(1,27)=90 ! [idx] 12C2_1H6
  map(2,27)=91 ! [idx] 12C_13C_1H6

! Molecule 28, PH3
  map(1,28)=92 ! [idx] 31P_1H3

! Molecule 29, COF2
  map(1,29)=93 ! [idx] 12C_16O_19F2
  map(2,29)=94 ! [idx] 13C_16O_19F2

! Molecule 30, SF6
  map(1,30)=95 ! [idx] 32S_19F6

! Molecule 31, H2S
  map(1,31)=96 ! [idx] 1H2_32S
  map(2,31)=97 ! [idx] 1H_34S_1H
  map(3,31)=98 ! [idx] 1H_33S_1H

! Molecule 32, HCOOH
  map(1,32)=99 ! [idx] 1H2_12C_16O2

! Molecule 33, HO2
  map(1,33)=100 ! [idx] 1H_16O2

! Molecule 34, O
  map(1,34)=101 ! [idx] 16O

! Molecule 35, ClONO2
  map(1,35)=102 ! [idx] 35Cl_16O_14N_16O2
  map(2,35)=103 ! [idx] 37Cl_16O_14N_16O2

! Molecule 36, NO+
  map(1,36)=104 ! [idx] 14N_16O+

! Molecule 37, HOBr
  map(1,37)=105 ! [idx] 1H_16O_79Br
  map(2,37)=106 ! [idx] 1H_16O_81Br

! Molecule 38, C2H4
  map(1,38)=107 ! [idx] 12C2_1H4
  map(2,38)=108 ! [idx] 12C_13C_1H4

! Molecule 39, CH3OH
  map(1,39)=109 ! [idx] 12C2_1H3_16O_1H

! Molecule 40, CH3Br
  map(1,40)=110 ! [idx] 12C_1H3_79Br
  map(2,40)=111 ! [idx] 12C_1H3_81Br

! Molecule 41, CH3CN
  map(1,41)=112 ! [idx] 12C2_1H3_14N

! Molecule 42, CF4
  map(1,42)=113 ! [idx] 12C_F4

! Molecule 43, C4H2
  map(1,43)=114 ! [idx] 12C4_1H2

! Molecule 44, HC3N
  map(1,44)=115 ! [idx] 1H_12C3_14N

! Molecule 45, H2
  map(1,45)=116 ! [idx] 1H
  map(2,45)=117 ! [idx] 2H

! Molecule 46, CS
  map(1,46)=118 ! [idx] 12C_32S
  map(2,46)=119 ! [idx] 13C_32S
  map(3,46)=120 ! [idx] 12C_34S
  map(4,46)=121 ! [idx] 13C_34S

! Molecule 47, SO3
  map(1,47)=122 ! [idx] 32S_16O3

! Molecule 48, C2N2
  map(1,48)=123 ! [idx] 12C2_14N2

! Molecule 49, COCl2
  map(1,49)=124 ! [idx] 12C_16O_35Cl2
  map(2,49)=125 ! [idx] 12C_16O_35Cl_37Cl
  return
end subroutine iso_idx_map_get

subroutine mlc_sng_get(mlc_sng)

! Purpose: Fills in an array containing all the HITRAN molecule names

! use htrn_cst,only:mlc_nbr_max_htrn ! [mdl] HITRAN constants, subroutines
  implicit none
! Output
  character(10),intent(out)::mlc_sng(mlc_nbr_max_htrn) ! [sng] Contains all HITRAN molecule names

! Fill in array for all molecules
  mlc_sng(idx_H2O)="H2O"
  mlc_sng(idx_CO2)="CO2"
  mlc_sng(idx_O3)="O3"
  mlc_sng(idx_N2O)="N2O"
  mlc_sng(idx_CO)="CO"
  mlc_sng(idx_CH4)="CH4"
  mlc_sng(idx_O2)="O2"
  mlc_sng(idx_NO)="NO"
  mlc_sng(idx_SO2)="SO2"
  mlc_sng(idx_NO2)="NO2"
  mlc_sng(idx_NH3)="NH3"
  mlc_sng(idx_HNO3)="HNO3"
  mlc_sng(idx_OH)="OH"
  mlc_sng(idx_HF)="HF"
  mlc_sng(idx_HCl)="HCl"
  mlc_sng(idx_HBr)="HBr"
  mlc_sng(idx_HI)="HI"
  mlc_sng(idx_ClO)="ClO"
  mlc_sng(idx_OCS)="OCS"
  mlc_sng(idx_H2CO)="H2CO"
  mlc_sng(idx_HOCl)="HOCl"
  mlc_sng(idx_N2)="N2"
  mlc_sng(idx_HCN)="HCN"
  mlc_sng(idx_CH3Cl)="CH3Cl"
  mlc_sng(idx_H2O2)="H2O2"
  mlc_sng(idx_C2H2)="C2H2"
  mlc_sng(idx_C2H6)="C2H6"
  mlc_sng(idx_PH3)="PH3"
  mlc_sng(idx_COF2)="COF2"
  mlc_sng(idx_SF6)="SF6"
  mlc_sng(idx_H2S)="H2S"
  mlc_sng(idx_HCOOH)="HCOOH"
  mlc_sng(idx_HO2)="HO2"
  mlc_sng(idx_O)="O"
  mlc_sng(idx_ClONO2)="ClONO2"
  mlc_sng(idx_NO_ion)="NO+"
  mlc_sng(idx_HOBr)="HOBr"
  mlc_sng(idx_C2H4)="C2H4"
  mlc_sng(idx_CH3OH)="CH3OH"
  mlc_sng(idx_CH3Br)="CH3Br"
  mlc_sng(idx_CH3CN)="CH3CN"
  mlc_sng(idx_CF4)="CF4"
  mlc_sng(idx_C4H2)="C4H2"
  mlc_sng(idx_HC3N)="HC3N"
  mlc_sng(idx_H2)="H2"
  mlc_sng(idx_CS)="CS"
  mlc_sng(idx_SO3)="SO3"
  mlc_sng(idx_C2N2)="C2N2"
  mlc_sng(idx_COCl2)="COCl2"
  return
end subroutine mlc_sng_get

subroutine iso_sng_get(iso_sng)

! Purpose: Fills array containing all HITRAN isotopomer names

! use htrn_cst,only:iso_nbr_max_htrn ! [mdl] HITRAN constants, subroutines
  implicit none
! Output
  character(20),intent(out)::iso_sng(iso_nbr_max_htrn) ! [sng] Contains all HITRAN isotopomer names

! Fill array for all isotopomers
  iso_sng(idx_1H2_16O)="1H2_16O"
  iso_sng(idx_1H2_18O)="1H2_18O"
  iso_sng(idx_1H2_17O)="1H2_17O"
  iso_sng(idx_1H_2H_16O)="1H_2H_16O"
  iso_sng(idx_1H_2H_18O)="1H_2H_18O"
  iso_sng(idx_1H_2H_17O)="1H_2H_17O"
  iso_sng(idx_2H_2H_16O)="2H_2H_16O"
  iso_sng(idx_12C_16O2)="12C_16O2"
  iso_sng(idx_13C_16O2)="13C_16O2"
  iso_sng(idx_16O_12C_18O)="16O_12C_18O"
  iso_sng(idx_16O_12C_17O)="16O_12C_17O"
  iso_sng(idx_16O_13C_18O)="16O_13C_18O"
  iso_sng(idx_16O_13C_17O)="16O_13C_17O"
  iso_sng(idx_12C_18O2)="12C_18O2"
  iso_sng(idx_17O_12C_18O)="17O_12C_18O"
  iso_sng(idx_12C_17O2)="12C_17O2"
  iso_sng(idx_13C_18O2)="13C_18O2"
  iso_sng(idx_18O_13C_17O)="18O_13C_17O"
  iso_sng(idx_16O3)="16O3"
  iso_sng(idx_16O_16O_18O)="16O_16O_18O"
  iso_sng(idx_16O_18O_16O)="16O_18O_16O"
  iso_sng(idx_16O_16O_17O)="16O_16O_17O"
  iso_sng(idx_16O_17O_16O)="16O_17O_16O"
  iso_sng(idx_14N2_16O)="14N2_16O"
  iso_sng(idx_14N_15N_16O)="14N_15N_16O"
  iso_sng(idx_15N_14N_16O)="15N_14N_16O"
  iso_sng(idx_14N2_18O)="14N2_18O"
  iso_sng(idx_14N2_17O)="14N2_17O"
  iso_sng(idx_12C_16O)="12C_16O"
  iso_sng(idx_13C_16O)="13C_16O"
  iso_sng(idx_12C_18O)="12C_18O"
  iso_sng(idx_12C_17O)="12C_17O"
  iso_sng(idx_13C_18O)="13C_18O"
  iso_sng(idx_13C_17O)="13C_17O"
  iso_sng(idx_12C_1H4)="12C_1H4"
  iso_sng(idx_13C_1H4)="13C_1H4"
  iso_sng(idx_12C_1H3_2H)="12C_1H3_2H"
  iso_sng(idx_13C_1H3_2H)="13C_1H3_2H"
  iso_sng(idx_16O2)="16O2"
  iso_sng(idx_16O_18O)="16O_18O"
  iso_sng(idx_16O_17O)="16O_17O"
  iso_sng(idx_14N_16O)="14N_16O"
  iso_sng(idx_15N_16O)="15N_16O"
  iso_sng(idx_14N_18O)="14N_18O"
  iso_sng(idx_32S_16O2)="32S_16O2"
  iso_sng(idx_34S_16O2)="34S_16O2"
  iso_sng(idx_14N_16O2)="14N_16O2"
  iso_sng(idx_14N_1H3)="14N_1H3"
  iso_sng(idx_15N_1H3)="15N_1H3"
  iso_sng(idx_1H_14N_16O3)="1H_14N_16O3"
  iso_sng(idx_1H_15N_16O3)="1H_15N_16O3"
  iso_sng(idx_16O_1H)="16O_1H"
  iso_sng(idx_18O_1H)="18O_1H"
  iso_sng(idx_16O_2H)="16O_2H"
  iso_sng(idx_1H_19F)="1H_19F"
  iso_sng(idx_2H_19F)="2H_19F"
  iso_sng(idx_1H_35Cl)="1H_35Cl"
  iso_sng(idx_1H_37Cl)="1H_37Cl"
  iso_sng(idx_2H_35Cl)="2H_35Cl"
  iso_sng(idx_2H_37Cl)="2H_37Cl"
  iso_sng(idx_1H_79Br)="1H_79Br"
  iso_sng(idx_1H_81Br)="1H_81Br"
  iso_sng(idx_2H_79Br)="2H_79Br"
  iso_sng(idx_2H_81Br)="2H_81Br"
  iso_sng(idx_1H_127I)="1H_127I"
  iso_sng(idx_2H_127I)="2H_127I"
  iso_sng(idx_35Cl_16O)="35Cl_16O"
  iso_sng(idx_37Cl_16O)="37Cl_16O"
  iso_sng(idx_16O_12C_32S)="16O_12C_32S"
  iso_sng(idx_16O_12C_34S)="16O_12C_34S"
  iso_sng(idx_16O_13C_32S)="16O_13C_32S"
  iso_sng(idx_16O_12C_33S)="16O_12C_33S"
  iso_sng(idx_18O_12C_32S)="18O_12C_32S"
  iso_sng(idx_1H2_12C_16O)="1H2_12C_16O"
  iso_sng(idx_1H2_13C_16O)="1H2_13C_16O"
  iso_sng(idx_1H2_12C_18O)="1H2_12C_18O"
  iso_sng(idx_1H_16O_35Cl)="1H_16O_35Cl"
  iso_sng(idx_1H_16O_37Cl)="1H_16O_37Cl"
  iso_sng(idx_14N2)="14N2"
  iso_sng(idx_14N_15N)="14N_15N"
  iso_sng(idx_1H_12C_14N)="1H_12C_14N"
  iso_sng(idx_1H_13C_14N)="1H_13C_14N"
  iso_sng(idx_1H_12C_15N)="1H_12C_15N"
  iso_sng(idx_12C_1H_35Cl)="12C_1H_35Cl"
  iso_sng(idx_12C_1H_37Cl)="12C_1H_37Cl"
  iso_sng(idx_1H2_16O2)="1H2_16O2"
  iso_sng(idx_12C2_1H2)="12C2_1H2"
  iso_sng(idx_1H_12C_13C_1H)="1H_12C_13C_1H"
  iso_sng(idx_1H_12C_12C_2H)="1H_12C_12C_2H"
  iso_sng(idx_12C2_1H6)="12C2_1H6"
  iso_sng(idx_12C_13C_1H6)="12C_13C_1H6"
  iso_sng(idx_31P_1H3)="31P_1H3"
  iso_sng(idx_12C_16O_19F2)="12C_16O_19F2"
  iso_sng(idx_13C_16O_19F2)="13C_16O_19F2"
  iso_sng(idx_32S_19F6)="32S_19F6"
  iso_sng(idx_1H2_32S)="1H2_32S"
  iso_sng(idx_1H_34S_1H)="1H_34S_1H"
  iso_sng(idx_1H_33S_1H)="1H_33S_1H"
  iso_sng(idx_1H2_12C_16O2)="1H2_12C_16O2"
  iso_sng(idx_1H_16O2)="1H_16O2"
  iso_sng(idx_16O)="16O"
  iso_sng(idx_35Cl_16O_14N_16O2)="35Cl_16O_14N_16O2"
  iso_sng(idx_37Cl_16O_14N_16O2)="37Cl_16O_14N_16O2"
  iso_sng(idx_14N_16O_ion)="14N_16O+"
  iso_sng(idx_1H_16O_79Br)="1H_16O_79Br"
  iso_sng(idx_1H_16O_81Br)="1H_16O_81Br"
  iso_sng(idx_12C2_1H4)="12C2_1H4"
  iso_sng(idx_12C_13C_1H4)="12C_13C_1H4"
  iso_sng(idx_12C2_1H3_16O_1H)="12C2_1H3_16O_1H"
  iso_sng(idx_12C_1H3_79Br)="12C_1H3_79Br"
  iso_sng(idx_12C_1H3_81Br)="12C_1H3_81Br"
  iso_sng(idx_12C2_1H3_14N)="12C2_1H3_14N"
  iso_sng(idx_12C_F4)="12C_F4"
  iso_sng(idx_12C4_1H2)="12C4_1H2"
  iso_sng(idx_1H_12C3_14N)="1H_12C3_14N"
  iso_sng(idx_1H)="1H"
  iso_sng(idx_2H)="2H"
  iso_sng(idx_12C_32S)="12C_32S"
  iso_sng(idx_13C_32S)="13C_32S"
  iso_sng(idx_12C_34S)="12C_34S"
  iso_sng(idx_13C_34S)="13C_34S"
  iso_sng(idx_32S_16O3)="32S_16O3"
  iso_sng(idx_12C2_14N2)="12C2_14N2"
  iso_sng(idx_12C_16O_35Cl2)="12C_16O_35Cl2"
  iso_sng(idx_12C_16O_35Cl_37Cl)="12C_16O_35Cl_37Cl"
  return
end subroutine iso_sng_get

end module htrn_mdl

