// $Id$

// Purpose: Implementation (declaration) of HITRAN classes

/* Copyright (C) 1997--2014 Charlie Zender
   This software is distributed under the terms of the GNU General Public License (GPL) Version 3
   See http://www.gnu.org/copyleft/gpl.html for full license text */

/* Usage: /home/zender/c++/htrn_c++.cc automatically generated by htrn on Wed Jun 12 10:58:29 2013

   Command: htrn

   Compilation:
   g++ -Wall -c -O -D$PVM_ARCH -I${HOME}/include ${HOME}/c++/htrn_c++.cc -o ${MY_OBJ_DIR}/htrn_c++.o
*/
#include <htrn_c++.hh> // HITRAN definitions

// Namespaces
using namespace htrn; // [nms] HITRAN namespace

// htrn_cls class

// Friendly functions begin

int // O [enm] Return success code
mmw_mlc_get // [fnc] Mean molecular weight of HITRAN molecules
(double *mmw_mlc) // O [kg mol-1] Mean molecular weight of HITRAN molecules
{
  // Purpose: Provide mean molecular weight of HITRAN molecules
  int rcd(0); // [enm] Return success code
  mmw_mlc[0]=1.0e36; // Zeroth element enables array addressing by mlc_id
  mmw_mlc[idx_H2O]=1.8015261e-02; // [kg mol-1] Mean molecular weight of H2O
  mmw_mlc[idx_CO2]=4.4009743e-02; // [kg mol-1] Mean molecular weight of CO2
  mmw_mlc[idx_O3]=4.7997832e-02; // [kg mol-1] Mean molecular weight of O3
  mmw_mlc[idx_N2O]=4.4012674e-02; // [kg mol-1] Mean molecular weight of N2O
  mmw_mlc[idx_CO]=2.8010445e-02; // [kg mol-1] Mean molecular weight of CO
  mmw_mlc[idx_CH4]=1.6043074e-02; // [kg mol-1] Mean molecular weight of CH4
  mmw_mlc[idx_O2]=3.1998575e-02; // [kg mol-1] Mean molecular weight of O2
  mmw_mlc[idx_NO]=3.0005630e-02; // [kg mol-1] Mean molecular weight of NO
  mmw_mlc[idx_SO2]=6.4046674e-02; // [kg mol-1] Mean molecular weight of SO2
  mmw_mlc[idx_NO2]=4.5992904e-02; // [kg mol-1] Mean molecular weight of NO2
  mmw_mlc[idx_NH3]=1.7030201e-02; // [kg mol-1] Mean molecular weight of NH3
  mmw_mlc[idx_HNO3]=6.2999296e-02; // [kg mol-1] Mean molecular weight of HNO3
  mmw_mlc[idx_OH]=1.7006907e-02; // [kg mol-1] Mean molecular weight of OH
  mmw_mlc[idx_HF]=2.0006386e-02; // [kg mol-1] Mean molecular weight of HF
  mmw_mlc[idx_HCl]=3.6460710e-02; // [kg mol-1] Mean molecular weight of HCl
  mmw_mlc[idx_HBr]=8.0911588e-02; // [kg mol-1] Mean molecular weight of HBr
  mmw_mlc[idx_HI]=1.2791245e-01; // [kg mol-1] Mean molecular weight of HI
  mmw_mlc[idx_ClO]=5.1447643e-02; // [kg mol-1] Mean molecular weight of ClO
  mmw_mlc[idx_OCS]=6.0071832e-02; // [kg mol-1] Mean molecular weight of OCS
  mmw_mlc[idx_H2CO]=3.0025657e-02; // [kg mol-1] Mean molecular weight of H2CO
  mmw_mlc[idx_HOCl]=5.2455469e-02; // [kg mol-1] Mean molecular weight of HOCl
  mmw_mlc[idx_N2]=2.8013474e-02; // [kg mol-1] Mean molecular weight of N2
  mmw_mlc[idx_HCN]=2.7025618e-02; // [kg mol-1] Mean molecular weight of HCN
  mmw_mlc[idx_CH3Cl]=5.0476203e-02; // [kg mol-1] Mean molecular weight of CH3Cl
  mmw_mlc[idx_H2O2]=3.4005480e-02; // [kg mol-1] Mean molecular weight of H2O2
  mmw_mlc[idx_C2H2]=2.6037999e-02; // [kg mol-1] Mean molecular weight of C2H2
  mmw_mlc[idx_C2H6]=3.0069000e-02; // [kg mol-1] Mean molecular weight of C2H6
  mmw_mlc[idx_PH3]=3.3997238e-02; // [kg mol-1] Mean molecular weight of PH3
  mmw_mlc[idx_COF2]=6.6002869e-02; // [kg mol-1] Mean molecular weight of COF2
  mmw_mlc[idx_SF6]=1.4596249e-01; // [kg mol-1] Mean molecular weight of SF6
  mmw_mlc[idx_H2S]=3.4079355e-02; // [kg mol-1] Mean molecular weight of H2S
  mmw_mlc[idx_HCOOH]=4.6005480e-02; // [kg mol-1] Mean molecular weight of HCOOH
  mmw_mlc[idx_HO2]=3.2997655e-02; // [kg mol-1] Mean molecular weight of HO2
  mmw_mlc[idx_O]=1.5994915e-02; // [kg mol-1] Mean molecular weight of O
  mmw_mlc[idx_ClONO2]=9.7440548e-02; // [kg mol-1] Mean molecular weight of ClONO2
  mmw_mlc[idx_NO_ion]=2.9997989e-02; // [kg mol-1] Mean molecular weight of NO+
  mmw_mlc[idx_HOBr]=9.6906346e-02; // [kg mol-1] Mean molecular weight of HOBr
  mmw_mlc[idx_C2H4]=2.8053350e-02; // [kg mol-1] Mean molecular weight of C2H4
  mmw_mlc[idx_CH3OH]=3.2026215e-02; // [kg mol-1] Mean molecular weight of CH3OH
  mmw_mlc[idx_CH3Br]=9.4927081e-02; // [kg mol-1] Mean molecular weight of CH3Br
  mmw_mlc[idx_CH3CN]=4.1026549e-02; // [kg mol-1] Mean molecular weight of CH3CN
  mmw_mlc[idx_CF4]=8.7993616e-02; // [kg mol-1] Mean molecular weight of CF4
  mmw_mlc[idx_C4H2]=5.0015650e-02; // [kg mol-1] Mean molecular weight of C4H2
  mmw_mlc[idx_HC3N]=5.1010899e-02; // [kg mol-1] Mean molecular weight of HC3N
  mmw_mlc[idx_H2]=2.0158067e-03; // [kg mol-1] Mean molecular weight of H2
  mmw_mlc[idx_CS]=4.4072299e-02; // [kg mol-1] Mean molecular weight of CS
  mmw_mlc[idx_SO3]=7.9956820e-02; // [kg mol-1] Mean molecular weight of SO3
  return rcd; // [enm] Return success code
} // end mmw_mlc_get()

int // O [enm] Return success code
mmw_iso_get // [fnc] Mean molecular weight of HITRAN isotopomers
(double *mmw_iso) // O [kg mol-1] Mean molecular weight of HITRAN isotopomers
{
  // Purpose: Provide mean molecular weight of HITRAN isotopomers
  int rcd(0); // [enm] Return success code
  mmw_iso[0]=1.0e36; // Zeroth element enables array addressing by iso_id
  mmw_iso[idx_1H2_16O]=1.8010565e-02; // [kg mol-1] Mean molecular weight of H2O isotope 1, 1H2_16O
  mmw_iso[idx_1H2_18O]=2.0014811e-02; // [kg mol-1] Mean molecular weight of H2O isotope 2, 1H2_18O
  mmw_iso[idx_1H2_17O]=1.9014780e-02; // [kg mol-1] Mean molecular weight of H2O isotope 3, 1H2_17O
  mmw_iso[idx_1H_2H_16O]=1.9016740e-02; // [kg mol-1] Mean molecular weight of H2O isotope 4, 1H_2H_16O
  mmw_iso[idx_1H_2H_18O]=2.1020985e-02; // [kg mol-1] Mean molecular weight of H2O isotope 5, 1H_2H_18O
  mmw_iso[idx_1H_2H_17O]=2.0020956e-02; // [kg mol-1] Mean molecular weight of H2O isotope 6, 1H_2H_17O
  mmw_iso[idx_12C_16O2]=4.3989830e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 1, 12C_16O2
  mmw_iso[idx_13C_16O2]=4.4993185e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 2, 13C_16O2
  mmw_iso[idx_16O_12C_18O]=4.5994076e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 3, 16O_12C_18O
  mmw_iso[idx_16O_12C_17O]=4.4994045e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 4, 16O_12C_17O
  mmw_iso[idx_16O_13C_18O]=4.6997431e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 5, 16O_13C_18O
  mmw_iso[idx_16O_13C_17O]=4.5997400e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 6, 16O_13C_17O
  mmw_iso[idx_12C_18O2]=4.7998322e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 7, 12C_18O2
  mmw_iso[idx_17O_12C_18O]=4.6998291e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 8, 17O_12C_18O
  mmw_iso[idx_12C_17O2]=4.5998262e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 9, 12C_17O2
  mmw_iso[idx_13C_18O2]=4.9001675e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 10, 13C_18O2
  mmw_iso[idx_18O_13C_17O]=4.8001646e-02; // [kg mol-1] Mean molecular weight of CO2 isotope 11, 18O_13C_17O
  mmw_iso[idx_16O3]=4.7984745e-02; // [kg mol-1] Mean molecular weight of O3 isotope 1, 16O3
  mmw_iso[idx_16O_16O_18O]=4.9988991e-02; // [kg mol-1] Mean molecular weight of O3 isotope 2, 16O_16O_18O
  mmw_iso[idx_16O_18O_16O]=4.9988991e-02; // [kg mol-1] Mean molecular weight of O3 isotope 3, 16O_18O_16O
  mmw_iso[idx_16O_16O_17O]=4.8988960e-02; // [kg mol-1] Mean molecular weight of O3 isotope 4, 16O_16O_17O
  mmw_iso[idx_16O_17O_16O]=4.8988960e-02; // [kg mol-1] Mean molecular weight of O3 isotope 5, 16O_17O_16O
  mmw_iso[idx_14N2_16O]=4.4001062e-02; // [kg mol-1] Mean molecular weight of N2O isotope 1, 14N2_16O
  mmw_iso[idx_14N_15N_16O]=4.4998096e-02; // [kg mol-1] Mean molecular weight of N2O isotope 2, 14N_15N_16O
  mmw_iso[idx_15N_14N_16O]=4.4998096e-02; // [kg mol-1] Mean molecular weight of N2O isotope 3, 15N_14N_16O
  mmw_iso[idx_14N2_18O]=4.6005308e-02; // [kg mol-1] Mean molecular weight of N2O isotope 4, 14N2_18O
  mmw_iso[idx_14N2_17O]=4.5005278e-02; // [kg mol-1] Mean molecular weight of N2O isotope 5, 14N2_17O
  mmw_iso[idx_12C_16O]=2.7994915e-02; // [kg mol-1] Mean molecular weight of CO isotope 1, 12C_16O
  mmw_iso[idx_13C_16O]=2.8998270e-02; // [kg mol-1] Mean molecular weight of CO isotope 2, 13C_16O
  mmw_iso[idx_12C_18O]=2.9999161e-02; // [kg mol-1] Mean molecular weight of CO isotope 3, 12C_18O
  mmw_iso[idx_12C_17O]=2.8999130e-02; // [kg mol-1] Mean molecular weight of CO isotope 4, 12C_17O
  mmw_iso[idx_13C_18O]=3.1002516e-02; // [kg mol-1] Mean molecular weight of CO isotope 5, 13C_18O
  mmw_iso[idx_13C_17O]=3.0002485e-02; // [kg mol-1] Mean molecular weight of CO isotope 6, 13C_17O
  mmw_iso[idx_12C_1H4]=1.6031300e-02; // [kg mol-1] Mean molecular weight of CH4 isotope 1, 12C_1H4
  mmw_iso[idx_13C_1H4]=1.7034655e-02; // [kg mol-1] Mean molecular weight of CH4 isotope 2, 13C_1H4
  mmw_iso[idx_12C_1H3_2H]=1.7037475e-02; // [kg mol-1] Mean molecular weight of CH4 isotope 3, 12C_1H3_2H
  mmw_iso[idx_13C_1H3_2H]=1.8040830e-02; // [kg mol-1] Mean molecular weight of CH4 isotope 4, 13C_1H3_2H
  mmw_iso[idx_16O2]=3.1989830e-02; // [kg mol-1] Mean molecular weight of O2 isotope 1, 16O2
  mmw_iso[idx_16O_18O]=3.3994076e-02; // [kg mol-1] Mean molecular weight of O2 isotope 2, 16O_18O
  mmw_iso[idx_16O_17O]=3.2994045e-02; // [kg mol-1] Mean molecular weight of O2 isotope 3, 16O_17O
  mmw_iso[idx_14N_16O]=2.9997989e-02; // [kg mol-1] Mean molecular weight of NO isotope 1, 14N_16O
  mmw_iso[idx_15N_16O]=3.0995023e-02; // [kg mol-1] Mean molecular weight of NO isotope 2, 15N_16O
  mmw_iso[idx_14N_18O]=3.2002234e-02; // [kg mol-1] Mean molecular weight of NO isotope 3, 14N_18O
  mmw_iso[idx_32S_16O2]=6.3961901e-02; // [kg mol-1] Mean molecular weight of SO2 isotope 1, 32S_16O2
  mmw_iso[idx_34S_16O2]=6.5957695e-02; // [kg mol-1] Mean molecular weight of SO2 isotope 2, 34S_16O2
  mmw_iso[idx_14N_16O2]=4.5992904e-02; // [kg mol-1] Mean molecular weight of NO2 isotope 1, 14N_16O2
  mmw_iso[idx_14N_1H3]=1.7026549e-02; // [kg mol-1] Mean molecular weight of NH3 isotope 1, 14N_1H3
  mmw_iso[idx_15N_1H3]=1.8023583e-02; // [kg mol-1] Mean molecular weight of NH3 isotope 2, 15N_1H3
  mmw_iso[idx_1H_14N_16O3]=6.2995644e-02; // [kg mol-1] Mean molecular weight of HNO3 isotope 1, 1H_14N_16O3
  mmw_iso[idx_1H_15N_16O3]=6.3992680e-02; // [kg mol-1] Mean molecular weight of HNO3 isotope 2, 1H_15N_16O3
  mmw_iso[idx_16O_1H]=1.7002740e-02; // [kg mol-1] Mean molecular weight of OH isotope 1, 16O_1H
  mmw_iso[idx_18O_1H]=1.9006986e-02; // [kg mol-1] Mean molecular weight of OH isotope 2, 18O_1H
  mmw_iso[idx_16O_2H]=1.8008915e-02; // [kg mol-1] Mean molecular weight of OH isotope 3, 16O_2H
  mmw_iso[idx_1H_19F]=2.0006229e-02; // [kg mol-1] Mean molecular weight of HF isotope 1, 1H_19F
  mmw_iso[idx_2H_19F]=2.1012404e-02; // [kg mol-1] Mean molecular weight of HF isotope 2, 2H_19F
  mmw_iso[idx_1H_35Cl]=3.5976678e-02; // [kg mol-1] Mean molecular weight of HCl isotope 1, 1H_35Cl
  mmw_iso[idx_1H_37Cl]=3.7973729e-02; // [kg mol-1] Mean molecular weight of HCl isotope 2, 1H_37Cl
  mmw_iso[idx_2H_35Cl]=3.6982853e-02; // [kg mol-1] Mean molecular weight of HCl isotope 3, 2H_35Cl
  mmw_iso[idx_2H_37Cl]=3.8979904e-02; // [kg mol-1] Mean molecular weight of HCl isotope 4, 2H_37Cl
  mmw_iso[idx_1H_79Br]=7.9926160e-02; // [kg mol-1] Mean molecular weight of HBr isotope 1, 1H_79Br
  mmw_iso[idx_1H_81Br]=8.1924115e-02; // [kg mol-1] Mean molecular weight of HBr isotope 2, 1H_81Br
  mmw_iso[idx_2H_79Br]=8.0932336e-02; // [kg mol-1] Mean molecular weight of HBr isotope 3, 2H_79Br
  mmw_iso[idx_2H_81Br]=8.2930289e-02; // [kg mol-1] Mean molecular weight of HBr isotope 4, 2H_81Br
  mmw_iso[idx_1H_127I]=1.2791230e-01; // [kg mol-1] Mean molecular weight of HI isotope 1, 1H_127I
  mmw_iso[idx_2H_127I]=1.2891847e-01; // [kg mol-1] Mean molecular weight of HI isotope 2, 2H_127I
  mmw_iso[idx_35Cl_16O]=5.0963768e-02; // [kg mol-1] Mean molecular weight of ClO isotope 1, 35Cl_16O
  mmw_iso[idx_37Cl_16O]=5.2960819e-02; // [kg mol-1] Mean molecular weight of ClO isotope 2, 37Cl_16O
  mmw_iso[idx_16O_12C_32S]=5.9966986e-02; // [kg mol-1] Mean molecular weight of OCS isotope 1, 16O_12C_32S
  mmw_iso[idx_16O_12C_34S]=6.1962780e-02; // [kg mol-1] Mean molecular weight of OCS isotope 2, 16O_12C_34S
  mmw_iso[idx_16O_13C_32S]=6.0970341e-02; // [kg mol-1] Mean molecular weight of OCS isotope 3, 16O_13C_32S
  mmw_iso[idx_16O_12C_33S]=6.0966371e-02; // [kg mol-1] Mean molecular weight of OCS isotope 4, 16O_12C_33S
  mmw_iso[idx_18O_12C_32S]=6.1971231e-02; // [kg mol-1] Mean molecular weight of OCS isotope 5, 18O_12C_32S
  mmw_iso[idx_1H2_12C_16O]=3.0010565e-02; // [kg mol-1] Mean molecular weight of H2CO isotope 1, 1H2_12C_16O
  mmw_iso[idx_1H2_13C_16O]=3.1013920e-02; // [kg mol-1] Mean molecular weight of H2CO isotope 2, 1H2_13C_16O
  mmw_iso[idx_1H2_12C_18O]=3.2014811e-02; // [kg mol-1] Mean molecular weight of H2CO isotope 3, 1H2_12C_18O
  mmw_iso[idx_1H_16O_35Cl]=5.1971593e-02; // [kg mol-1] Mean molecular weight of HOCl isotope 1, 1H_16O_35Cl
  mmw_iso[idx_1H_16O_37Cl]=5.3968644e-02; // [kg mol-1] Mean molecular weight of HOCl isotope 2, 1H_16O_37Cl
  mmw_iso[idx_14N2]=2.8006147e-02; // [kg mol-1] Mean molecular weight of N2 isotope 1, 14N2
  mmw_iso[idx_14N_15N]=2.9997989e-02; // [kg mol-1] Mean molecular weight of N2 isotope 2, 14N_15N
  mmw_iso[idx_1H_12C_14N]=2.7010899e-02; // [kg mol-1] Mean molecular weight of HCN isotope 1, 1H_12C_14N
  mmw_iso[idx_1H_13C_14N]=2.8014254e-02; // [kg mol-1] Mean molecular weight of HCN isotope 2, 1H_13C_14N
  mmw_iso[idx_1H_12C_15N]=2.8007933e-02; // [kg mol-1] Mean molecular weight of HCN isotope 3, 1H_12C_15N
  mmw_iso[idx_12C_1H_35Cl]=4.9992328e-02; // [kg mol-1] Mean molecular weight of CH3Cl isotope 1, 12C_1H_35Cl
  mmw_iso[idx_12C_1H_37Cl]=5.1989379e-02; // [kg mol-1] Mean molecular weight of CH3Cl isotope 2, 12C_1H_37Cl
  mmw_iso[idx_1H2_16O2]=3.4005480e-02; // [kg mol-1] Mean molecular weight of H2O2 isotope 1, 1H2_16O2
  mmw_iso[idx_12C2_1H2]=2.6015650e-02; // [kg mol-1] Mean molecular weight of C2H2 isotope 1, 12C2_1H2
  mmw_iso[idx_1H_12C_13C_1H]=2.7019005e-02; // [kg mol-1] Mean molecular weight of C2H2 isotope 2, 1H_12C_13C_1H
  mmw_iso[idx_1H_12C_12C_2H]=2.7021825e-02; // [kg mol-1] Mean molecular weight of C2H2 isotope 3, 1H_12C_12C_2H
  mmw_iso[idx_12C2_1H6]=3.0046950e-02; // [kg mol-1] Mean molecular weight of C2H6 isotope 1, 12C2_1H6
  mmw_iso[idx_12C_13C_1H6]=3.1050305e-02; // [kg mol-1] Mean molecular weight of C2H6 isotope 2, 12C_13C_1H6
  mmw_iso[idx_31P_1H3]=3.3997238e-02; // [kg mol-1] Mean molecular weight of PH3 isotope 1, 31P_1H3
  mmw_iso[idx_12C_16O_19F2]=6.5991722e-02; // [kg mol-1] Mean molecular weight of COF2 isotope 1, 12C_16O_19F2
  mmw_iso[idx_13C_16O_19F2]=6.6995083e-02; // [kg mol-1] Mean molecular weight of COF2 isotope 2, 13C_16O_19F2
  mmw_iso[idx_32S_19F6]=1.4596249e-01; // [kg mol-1] Mean molecular weight of SF6 isotope 1, 32S_19F6
  mmw_iso[idx_1H2_32S]=3.3987721e-02; // [kg mol-1] Mean molecular weight of H2S isotope 1, 1H2_32S
  mmw_iso[idx_1H_34S_1H]=3.5983515e-02; // [kg mol-1] Mean molecular weight of H2S isotope 2, 1H_34S_1H
  mmw_iso[idx_1H_33S_1H]=3.4987105e-02; // [kg mol-1] Mean molecular weight of H2S isotope 3, 1H_33S_1H
  mmw_iso[idx_1H2_12C_16O2]=4.6005480e-02; // [kg mol-1] Mean molecular weight of HCOOH isotope 1, 1H2_12C_16O2
  mmw_iso[idx_1H_16O2]=3.2997655e-02; // [kg mol-1] Mean molecular weight of HO2 isotope 1, 1H_16O2
  mmw_iso[idx_16O]=1.5994915e-02; // [kg mol-1] Mean molecular weight of O isotope 1, 16O
  mmw_iso[idx_35Cl_16O_14N_16O2]=9.6956672e-02; // [kg mol-1] Mean molecular weight of ClONO2 isotope 1, 35Cl_16O_14N_16O2
  mmw_iso[idx_37Cl_16O_14N_16O2]=9.8953723e-02; // [kg mol-1] Mean molecular weight of ClONO2 isotope 2, 37Cl_16O_14N_16O2
  mmw_iso[idx_14N_16O_ion]=2.9997989e-02; // [kg mol-1] Mean molecular weight of NO+ isotope 1, 14N_16O+
  mmw_iso[idx_1H_16O_79Br]=9.5921076e-02; // [kg mol-1] Mean molecular weight of HOBr isotope 1, 1H_16O_79Br
  mmw_iso[idx_1H_16O_81Br]=9.7919027e-02; // [kg mol-1] Mean molecular weight of HOBr isotope 2, 1H_16O_81Br
  mmw_iso[idx_12C2_1H4]=2.8031300e-02; // [kg mol-1] Mean molecular weight of C2H4 isotope 1, 12C2_1H4
  mmw_iso[idx_12C_13C_1H4]=2.9034655e-02; // [kg mol-1] Mean molecular weight of C2H4 isotope 2, 12C_13C_1H4
  mmw_iso[idx_12C2_1H3_16O_1H]=3.2026215e-02; // [kg mol-1] Mean molecular weight of CH3OH isotope 1, 12C2_1H3_16O_1H
  mmw_iso[idx_12C_1H3_79Br]=9.3941811e-02; // [kg mol-1] Mean molecular weight of CH3Br isotope 1, 12C_1H3_79Br
  mmw_iso[idx_12C_1H3_81Br]=9.5939764e-02; // [kg mol-1] Mean molecular weight of CH3Br isotope 2, 12C_1H3_81Br
  mmw_iso[idx_12C2_1H3_14N]=4.1026549e-02; // [kg mol-1] Mean molecular weight of CH3CN isotope 1, 12C2_1H3_14N
  mmw_iso[idx_12C_F4]=8.7993616e-02; // [kg mol-1] Mean molecular weight of CF4 isotope 1, 12C_F4
  mmw_iso[idx_12C4_1H2]=5.0015650e-02; // [kg mol-1] Mean molecular weight of C4H2 isotope 1, 12C4_1H2
  mmw_iso[idx_1H_12C3_14N]=5.1010899e-02; // [kg mol-1] Mean molecular weight of HC3N isotope 1, 1H_12C3_14N
  mmw_iso[idx_1H]=2.0156500e-03; // [kg mol-1] Mean molecular weight of H2 isotope 1, 1H
  mmw_iso[idx_2H]=3.0218250e-03; // [kg mol-1] Mean molecular weight of H2 isotope 2, 2H
  mmw_iso[idx_12C_32S]=4.3971036e-02; // [kg mol-1] Mean molecular weight of CS isotope 1, 12C_32S
  mmw_iso[idx_13C_32S]=4.5966787e-02; // [kg mol-1] Mean molecular weight of CS isotope 2, 13C_32S
  mmw_iso[idx_12C_34S]=4.4974368e-02; // [kg mol-1] Mean molecular weight of CS isotope 3, 12C_34S
  mmw_iso[idx_13C_34S]=4.4970399e-02; // [kg mol-1] Mean molecular weight of CS isotope 4, 13C_34S
  mmw_iso[idx_32S_16O3]=7.9956820e-02; // [kg mol-1] Mean molecular weight of SO3 isotope 1, 32S_16O3
  return rcd; // [enm] Return success code
} // end mmw_iso_get()

int // O [enm] Return success code
mlc_sng_get // [fnc] HITRAN molecule names
(std::string *mlc_sng) // O [sng] HITRAN molecule names
{
  // Purpose: Get array of molecule strings
  int rcd(0); // [enm] Return success code
  mlc_sng[0]="Undefined"; // Zeroth element enables array addressing by mlc_id
  mlc_sng[idx_H2O]="H2O";
  mlc_sng[idx_CO2]="CO2";
  mlc_sng[idx_O3]="O3";
  mlc_sng[idx_N2O]="N2O";
  mlc_sng[idx_CO]="CO";
  mlc_sng[idx_CH4]="CH4";
  mlc_sng[idx_O2]="O2";
  mlc_sng[idx_NO]="NO";
  mlc_sng[idx_SO2]="SO2";
  mlc_sng[idx_NO2]="NO2";
  mlc_sng[idx_NH3]="NH3";
  mlc_sng[idx_HNO3]="HNO3";
  mlc_sng[idx_OH]="OH";
  mlc_sng[idx_HF]="HF";
  mlc_sng[idx_HCl]="HCl";
  mlc_sng[idx_HBr]="HBr";
  mlc_sng[idx_HI]="HI";
  mlc_sng[idx_ClO]="ClO";
  mlc_sng[idx_OCS]="OCS";
  mlc_sng[idx_H2CO]="H2CO";
  mlc_sng[idx_HOCl]="HOCl";
  mlc_sng[idx_N2]="N2";
  mlc_sng[idx_HCN]="HCN";
  mlc_sng[idx_CH3Cl]="CH3Cl";
  mlc_sng[idx_H2O2]="H2O2";
  mlc_sng[idx_C2H2]="C2H2";
  mlc_sng[idx_C2H6]="C2H6";
  mlc_sng[idx_PH3]="PH3";
  mlc_sng[idx_COF2]="COF2";
  mlc_sng[idx_SF6]="SF6";
  mlc_sng[idx_H2S]="H2S";
  mlc_sng[idx_HCOOH]="HCOOH";
  mlc_sng[idx_HO2]="HO2";
  mlc_sng[idx_O]="O";
  mlc_sng[idx_ClONO2]="ClONO2";
  mlc_sng[idx_NO_ion]="NO+";
  mlc_sng[idx_HOBr]="HOBr";
  mlc_sng[idx_C2H4]="C2H4";
  mlc_sng[idx_CH3OH]="CH3OH";
  mlc_sng[idx_CH3Br]="CH3Br";
  mlc_sng[idx_CH3CN]="CH3CN";
  mlc_sng[idx_CF4]="CF4";
  mlc_sng[idx_C4H2]="C4H2";
  mlc_sng[idx_HC3N]="HC3N";
  mlc_sng[idx_H2]="H2";
  mlc_sng[idx_CS]="CS";
  mlc_sng[idx_SO3]="SO3";
  return rcd; // [enm] Return success code
} // end mlc_sng_get()

int // O [enm] Return success code
iso_sng_get // [fnc] HITRAN isotopomer names
(std::string *iso_sng) // O [sng] HITRAN isotopomer names
{
  // Purpose: Get array of isotopomer strings
  int rcd(0); // [enm] Return success code
  iso_sng[0]="Undefined"; // Zeroth element enables array addressing by iso_id
  iso_sng[idx_1H2_16O]="1H2_16O";
  iso_sng[idx_1H2_18O]="1H2_18O";
  iso_sng[idx_1H2_17O]="1H2_17O";
  iso_sng[idx_1H_2H_16O]="1H_2H_16O";
  iso_sng[idx_1H_2H_18O]="1H_2H_18O";
  iso_sng[idx_1H_2H_17O]="1H_2H_17O";
  iso_sng[idx_12C_16O2]="12C_16O2";
  iso_sng[idx_13C_16O2]="13C_16O2";
  iso_sng[idx_16O_12C_18O]="16O_12C_18O";
  iso_sng[idx_16O_12C_17O]="16O_12C_17O";
  iso_sng[idx_16O_13C_18O]="16O_13C_18O";
  iso_sng[idx_16O_13C_17O]="16O_13C_17O";
  iso_sng[idx_12C_18O2]="12C_18O2";
  iso_sng[idx_17O_12C_18O]="17O_12C_18O";
  iso_sng[idx_12C_17O2]="12C_17O2";
  iso_sng[idx_13C_18O2]="13C_18O2";
  iso_sng[idx_18O_13C_17O]="18O_13C_17O";
  iso_sng[idx_16O3]="16O3";
  iso_sng[idx_16O_16O_18O]="16O_16O_18O";
  iso_sng[idx_16O_18O_16O]="16O_18O_16O";
  iso_sng[idx_16O_16O_17O]="16O_16O_17O";
  iso_sng[idx_16O_17O_16O]="16O_17O_16O";
  iso_sng[idx_14N2_16O]="14N2_16O";
  iso_sng[idx_14N_15N_16O]="14N_15N_16O";
  iso_sng[idx_15N_14N_16O]="15N_14N_16O";
  iso_sng[idx_14N2_18O]="14N2_18O";
  iso_sng[idx_14N2_17O]="14N2_17O";
  iso_sng[idx_12C_16O]="12C_16O";
  iso_sng[idx_13C_16O]="13C_16O";
  iso_sng[idx_12C_18O]="12C_18O";
  iso_sng[idx_12C_17O]="12C_17O";
  iso_sng[idx_13C_18O]="13C_18O";
  iso_sng[idx_13C_17O]="13C_17O";
  iso_sng[idx_12C_1H4]="12C_1H4";
  iso_sng[idx_13C_1H4]="13C_1H4";
  iso_sng[idx_12C_1H3_2H]="12C_1H3_2H";
  iso_sng[idx_13C_1H3_2H]="13C_1H3_2H";
  iso_sng[idx_16O2]="16O2";
  iso_sng[idx_16O_18O]="16O_18O";
  iso_sng[idx_16O_17O]="16O_17O";
  iso_sng[idx_14N_16O]="14N_16O";
  iso_sng[idx_15N_16O]="15N_16O";
  iso_sng[idx_14N_18O]="14N_18O";
  iso_sng[idx_32S_16O2]="32S_16O2";
  iso_sng[idx_34S_16O2]="34S_16O2";
  iso_sng[idx_14N_16O2]="14N_16O2";
  iso_sng[idx_14N_1H3]="14N_1H3";
  iso_sng[idx_15N_1H3]="15N_1H3";
  iso_sng[idx_1H_14N_16O3]="1H_14N_16O3";
  iso_sng[idx_1H_15N_16O3]="1H_15N_16O3";
  iso_sng[idx_16O_1H]="16O_1H";
  iso_sng[idx_18O_1H]="18O_1H";
  iso_sng[idx_16O_2H]="16O_2H";
  iso_sng[idx_1H_19F]="1H_19F";
  iso_sng[idx_2H_19F]="2H_19F";
  iso_sng[idx_1H_35Cl]="1H_35Cl";
  iso_sng[idx_1H_37Cl]="1H_37Cl";
  iso_sng[idx_2H_35Cl]="2H_35Cl";
  iso_sng[idx_2H_37Cl]="2H_37Cl";
  iso_sng[idx_1H_79Br]="1H_79Br";
  iso_sng[idx_1H_81Br]="1H_81Br";
  iso_sng[idx_2H_79Br]="2H_79Br";
  iso_sng[idx_2H_81Br]="2H_81Br";
  iso_sng[idx_1H_127I]="1H_127I";
  iso_sng[idx_2H_127I]="2H_127I";
  iso_sng[idx_35Cl_16O]="35Cl_16O";
  iso_sng[idx_37Cl_16O]="37Cl_16O";
  iso_sng[idx_16O_12C_32S]="16O_12C_32S";
  iso_sng[idx_16O_12C_34S]="16O_12C_34S";
  iso_sng[idx_16O_13C_32S]="16O_13C_32S";
  iso_sng[idx_16O_12C_33S]="16O_12C_33S";
  iso_sng[idx_18O_12C_32S]="18O_12C_32S";
  iso_sng[idx_1H2_12C_16O]="1H2_12C_16O";
  iso_sng[idx_1H2_13C_16O]="1H2_13C_16O";
  iso_sng[idx_1H2_12C_18O]="1H2_12C_18O";
  iso_sng[idx_1H_16O_35Cl]="1H_16O_35Cl";
  iso_sng[idx_1H_16O_37Cl]="1H_16O_37Cl";
  iso_sng[idx_14N2]="14N2";
  iso_sng[idx_14N_15N]="14N_15N";
  iso_sng[idx_1H_12C_14N]="1H_12C_14N";
  iso_sng[idx_1H_13C_14N]="1H_13C_14N";
  iso_sng[idx_1H_12C_15N]="1H_12C_15N";
  iso_sng[idx_12C_1H_35Cl]="12C_1H_35Cl";
  iso_sng[idx_12C_1H_37Cl]="12C_1H_37Cl";
  iso_sng[idx_1H2_16O2]="1H2_16O2";
  iso_sng[idx_12C2_1H2]="12C2_1H2";
  iso_sng[idx_1H_12C_13C_1H]="1H_12C_13C_1H";
  iso_sng[idx_1H_12C_12C_2H]="1H_12C_12C_2H";
  iso_sng[idx_12C2_1H6]="12C2_1H6";
  iso_sng[idx_12C_13C_1H6]="12C_13C_1H6";
  iso_sng[idx_31P_1H3]="31P_1H3";
  iso_sng[idx_12C_16O_19F2]="12C_16O_19F2";
  iso_sng[idx_13C_16O_19F2]="13C_16O_19F2";
  iso_sng[idx_32S_19F6]="32S_19F6";
  iso_sng[idx_1H2_32S]="1H2_32S";
  iso_sng[idx_1H_34S_1H]="1H_34S_1H";
  iso_sng[idx_1H_33S_1H]="1H_33S_1H";
  iso_sng[idx_1H2_12C_16O2]="1H2_12C_16O2";
  iso_sng[idx_1H_16O2]="1H_16O2";
  iso_sng[idx_16O]="16O";
  iso_sng[idx_35Cl_16O_14N_16O2]="35Cl_16O_14N_16O2";
  iso_sng[idx_37Cl_16O_14N_16O2]="37Cl_16O_14N_16O2";
  iso_sng[idx_14N_16O_ion]="14N_16O+";
  iso_sng[idx_1H_16O_79Br]="1H_16O_79Br";
  iso_sng[idx_1H_16O_81Br]="1H_16O_81Br";
  iso_sng[idx_12C2_1H4]="12C2_1H4";
  iso_sng[idx_12C_13C_1H4]="12C_13C_1H4";
  iso_sng[idx_12C2_1H3_16O_1H]="12C2_1H3_16O_1H";
  iso_sng[idx_12C_1H3_79Br]="12C_1H3_79Br";
  iso_sng[idx_12C_1H3_81Br]="12C_1H3_81Br";
  iso_sng[idx_12C2_1H3_14N]="12C2_1H3_14N";
  iso_sng[idx_12C_F4]="12C_F4";
  iso_sng[idx_12C4_1H2]="12C4_1H2";
  iso_sng[idx_1H_12C3_14N]="1H_12C3_14N";
  iso_sng[idx_1H]="1H";
  iso_sng[idx_2H]="2H";
  iso_sng[idx_12C_32S]="12C_32S";
  iso_sng[idx_13C_32S]="13C_32S";
  iso_sng[idx_12C_34S]="12C_34S";
  iso_sng[idx_13C_34S]="13C_34S";
  iso_sng[idx_32S_16O3]="32S_16O3";
  return rcd; // [enm] Return success code
} // end iso_sng_get()

int // O [enm] Return success code
rtl_fnc_tpt_xpn_get // [fnc] Exponent defining temperature dependence of rotational partition function
(double *xpn) // O [frc] Exponent defining temperature dependence of rotational partition function
{
  /* Purpose: Fills an array containing the exponent which defines
     the temperature dependence of the rotational partition function
     for each HITRAN molecule.
     Exponent is 1 for linear molecules (e.g., CO2, NO, N2O, CO), 3/2 for nonlinear molecules (e.g., H2O, O3, CH4)
     See Lio92 p. 33 (2.2.22a) */

  int rcd(0); // [enm] Return success code
  xpn[0]=1.0e36; // Zeroth element enables array addressing by mlc_id
  xpn[idx_H2O]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_CO2]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_O3]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_N2O]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_CO]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_CH4]=1.5; // Group 3, Spherical Rotors
  xpn[idx_O2]=1.0; // Group 5, Triplet Ground Electronic States 
  xpn[idx_NO]=1.0; // Group 6, Doublet Ground Electronic States (Half Integer J)
  xpn[idx_SO2]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_NO2]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_NH3]=1.5; // Group 4, Symmetric Rotors
  xpn[idx_HNO3]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_OH]=1.0; // Group 6, Doublet Ground Electronic States (Half Integer J)
  xpn[idx_HF]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_HCl]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_HBr]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_HI]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_ClO]=1.0; // Group 6, Doublet Ground Electronic States (Half Integer J)
  xpn[idx_OCS]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_H2CO]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_HOCl]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_N2]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_HCN]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_CH3Cl]=1.5; // Group 4, Symmetric Rotors
  xpn[idx_H2O2]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_C2H2]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_C2H6]=1.5; // Group 4, Symmetric Rotors
  xpn[idx_PH3]=1.5; // Group 4, Symmetric Rotors
  xpn[idx_COF2]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_SF6]=1.5; // Group 4, Symmetric Rotors
  xpn[idx_H2S]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_HCOOH]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_HO2]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_O]=1.5; // Group 0, Unknown group
  xpn[idx_ClONO2]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_NO_ion]=1.0; // Group 2, Diatomic and Linear Molecules with Integer J
  xpn[idx_HOBr]=1.5; // Group 1, Asymmetric Rotors
  xpn[idx_C2H4]=1.5; // Group 0, Unknown group
  xpn[idx_CH3OH]=1.5; // Group 0, Unknown group
  xpn[idx_CH3Br]=1.5; // Group 0, Unknown group
  xpn[idx_CH3CN]=1.5; // Group 0, Unknown group
  xpn[idx_CF4]=1.5; // Group 0, Unknown group
  xpn[idx_C4H2]=1.5; // Group 0, Unknown group
  xpn[idx_HC3N]=1.5; // Group 0, Unknown group
  xpn[idx_H2]=1.5; // Group 0, Unknown group
  xpn[idx_CS]=1.5; // Group 0, Unknown group
  xpn[idx_SO3]=1.5; // Group 0, Unknown group
  return rcd; // [enm] Return success code
} // end rtl_fnc_tpt_xpn_get()

int // O [enm] Return success code
iso_idx_map_get // [fnc] Map [mlc_id,iso_id]->istpmr_id
(short map[htrn::mlc_nbr_max_htrn+1][htrn::iso_per_mlc_nbr_max_htrn+1]) // O [map] Map [mlc_id,iso_id]->istpmr_id
{
/* Purpose: Fill array which maps molecular and isotopic indices to isotopomer index */

  int rcd(0); // [enm] Return success code
  int iso_idx; // [idx] HITRAN isotope index
  int mlc_idx; // [idx] HITRAN molecule index

  // Initialize the map
  for(mlc_idx=0;mlc_idx<=mlc_nbr_max_htrn;mlc_idx++){
    for(iso_idx=0;iso_idx<=iso_per_mlc_nbr_max_htrn;iso_idx++){
       map[mlc_idx][iso_idx]=0;
    } // end loop over iso
  } // end loop over mlc

  // Fill in map for all valid isotopomers

  //  Molecule 1, H2O
  map[1][1]=1; // [idx] 1H2_16O
  map[1][2]=2; // [idx] 1H2_18O
  map[1][3]=3; // [idx] 1H2_17O
  map[1][4]=4; // [idx] 1H_2H_16O
  map[1][5]=5; // [idx] 1H_2H_18O
  map[1][6]=6; // [idx] 1H_2H_17O

  //  Molecule 2, CO2
  map[2][1]=7; // [idx] 12C_16O2
  map[2][2]=8; // [idx] 13C_16O2
  map[2][3]=9; // [idx] 16O_12C_18O
  map[2][4]=10; // [idx] 16O_12C_17O
  map[2][5]=11; // [idx] 16O_13C_18O
  map[2][6]=12; // [idx] 16O_13C_17O
  map[2][7]=13; // [idx] 12C_18O2
  map[2][8]=14; // [idx] 17O_12C_18O
  map[2][9]=15; // [idx] 12C_17O2
  map[2][10]=16; // [idx] 13C_18O2
  map[2][11]=17; // [idx] 18O_13C_17O

  //  Molecule 3, O3
  map[3][1]=18; // [idx] 16O3
  map[3][2]=19; // [idx] 16O_16O_18O
  map[3][3]=20; // [idx] 16O_18O_16O
  map[3][4]=21; // [idx] 16O_16O_17O
  map[3][5]=22; // [idx] 16O_17O_16O

  //  Molecule 4, N2O
  map[4][1]=23; // [idx] 14N2_16O
  map[4][2]=24; // [idx] 14N_15N_16O
  map[4][3]=25; // [idx] 15N_14N_16O
  map[4][4]=26; // [idx] 14N2_18O
  map[4][5]=27; // [idx] 14N2_17O

  //  Molecule 5, CO
  map[5][1]=28; // [idx] 12C_16O
  map[5][2]=29; // [idx] 13C_16O
  map[5][3]=30; // [idx] 12C_18O
  map[5][4]=31; // [idx] 12C_17O
  map[5][5]=32; // [idx] 13C_18O
  map[5][6]=33; // [idx] 13C_17O

  //  Molecule 6, CH4
  map[6][1]=34; // [idx] 12C_1H4
  map[6][2]=35; // [idx] 13C_1H4
  map[6][3]=36; // [idx] 12C_1H3_2H
  map[6][4]=37; // [idx] 13C_1H3_2H

  //  Molecule 7, O2
  map[7][1]=38; // [idx] 16O2
  map[7][2]=39; // [idx] 16O_18O
  map[7][3]=40; // [idx] 16O_17O

  //  Molecule 8, NO
  map[8][1]=41; // [idx] 14N_16O
  map[8][2]=42; // [idx] 15N_16O
  map[8][3]=43; // [idx] 14N_18O

  //  Molecule 9, SO2
  map[9][1]=44; // [idx] 32S_16O2
  map[9][2]=45; // [idx] 34S_16O2

  //  Molecule 10, NO2
  map[10][1]=46; // [idx] 14N_16O2

  //  Molecule 11, NH3
  map[11][1]=47; // [idx] 14N_1H3
  map[11][2]=48; // [idx] 15N_1H3

  //  Molecule 12, HNO3
  map[12][1]=49; // [idx] 1H_14N_16O3
  map[12][2]=50; // [idx] 1H_15N_16O3

  //  Molecule 13, OH
  map[13][1]=51; // [idx] 16O_1H
  map[13][2]=52; // [idx] 18O_1H
  map[13][3]=53; // [idx] 16O_2H

  //  Molecule 14, HF
  map[14][1]=54; // [idx] 1H_19F
  map[14][2]=55; // [idx] 2H_19F

  //  Molecule 15, HCl
  map[15][1]=56; // [idx] 1H_35Cl
  map[15][2]=57; // [idx] 1H_37Cl
  map[15][3]=58; // [idx] 2H_35Cl
  map[15][4]=59; // [idx] 2H_37Cl

  //  Molecule 16, HBr
  map[16][1]=60; // [idx] 1H_79Br
  map[16][2]=61; // [idx] 1H_81Br
  map[16][3]=62; // [idx] 2H_79Br
  map[16][4]=63; // [idx] 2H_81Br

  //  Molecule 17, HI
  map[17][1]=64; // [idx] 1H_127I
  map[17][2]=65; // [idx] 2H_127I

  //  Molecule 18, ClO
  map[18][1]=66; // [idx] 35Cl_16O
  map[18][2]=67; // [idx] 37Cl_16O

  //  Molecule 19, OCS
  map[19][1]=68; // [idx] 16O_12C_32S
  map[19][2]=69; // [idx] 16O_12C_34S
  map[19][3]=70; // [idx] 16O_13C_32S
  map[19][4]=71; // [idx] 16O_12C_33S
  map[19][5]=72; // [idx] 18O_12C_32S

  //  Molecule 20, H2CO
  map[20][1]=73; // [idx] 1H2_12C_16O
  map[20][2]=74; // [idx] 1H2_13C_16O
  map[20][3]=75; // [idx] 1H2_12C_18O

  //  Molecule 21, HOCl
  map[21][1]=76; // [idx] 1H_16O_35Cl
  map[21][2]=77; // [idx] 1H_16O_37Cl

  //  Molecule 22, N2
  map[22][1]=78; // [idx] 14N2
  map[22][2]=79; // [idx] 14N_15N

  //  Molecule 23, HCN
  map[23][1]=80; // [idx] 1H_12C_14N
  map[23][2]=81; // [idx] 1H_13C_14N
  map[23][3]=82; // [idx] 1H_12C_15N

  //  Molecule 24, CH3Cl
  map[24][1]=83; // [idx] 12C_1H_35Cl
  map[24][2]=84; // [idx] 12C_1H_37Cl

  //  Molecule 25, H2O2
  map[25][1]=85; // [idx] 1H2_16O2

  //  Molecule 26, C2H2
  map[26][1]=86; // [idx] 12C2_1H2
  map[26][2]=87; // [idx] 1H_12C_13C_1H
  map[26][3]=88; // [idx] 1H_12C_12C_2H

  //  Molecule 27, C2H6
  map[27][1]=89; // [idx] 12C2_1H6
  map[27][2]=90; // [idx] 12C_13C_1H6

  //  Molecule 28, PH3
  map[28][1]=91; // [idx] 31P_1H3

  //  Molecule 29, COF2
  map[29][1]=92; // [idx] 12C_16O_19F2
  map[29][2]=93; // [idx] 13C_16O_19F2

  //  Molecule 30, SF6
  map[30][1]=94; // [idx] 32S_19F6

  //  Molecule 31, H2S
  map[31][1]=95; // [idx] 1H2_32S
  map[31][2]=96; // [idx] 1H_34S_1H
  map[31][3]=97; // [idx] 1H_33S_1H

  //  Molecule 32, HCOOH
  map[32][1]=98; // [idx] 1H2_12C_16O2

  //  Molecule 33, HO2
  map[33][1]=99; // [idx] 1H_16O2

  //  Molecule 34, O
  map[34][1]=100; // [idx] 16O

  //  Molecule 35, ClONO2
  map[35][1]=101; // [idx] 35Cl_16O_14N_16O2
  map[35][2]=102; // [idx] 37Cl_16O_14N_16O2

  //  Molecule 36, NO+
  map[36][1]=103; // [idx] 14N_16O+

  //  Molecule 37, HOBr
  map[37][1]=104; // [idx] 1H_16O_79Br
  map[37][2]=105; // [idx] 1H_16O_81Br

  //  Molecule 38, C2H4
  map[38][1]=106; // [idx] 12C2_1H4
  map[38][2]=107; // [idx] 12C_13C_1H4

  //  Molecule 39, CH3OH
  map[39][1]=108; // [idx] 12C2_1H3_16O_1H

  //  Molecule 40, CH3Br
  map[40][1]=109; // [idx] 12C_1H3_79Br
  map[40][2]=110; // [idx] 12C_1H3_81Br

  //  Molecule 41, CH3CN
  map[41][1]=111; // [idx] 12C2_1H3_14N

  //  Molecule 42, CF4
  map[42][1]=112; // [idx] 12C_F4

  //  Molecule 43, C4H2
  map[43][1]=113; // [idx] 12C4_1H2

  //  Molecule 44, HC3N
  map[44][1]=114; // [idx] 1H_12C3_14N

  //  Molecule 45, H2
  map[45][1]=115; // [idx] 1H
  map[45][2]=116; // [idx] 2H

  //  Molecule 46, CS
  map[46][1]=117; // [idx] 12C_32S
  map[46][2]=118; // [idx] 13C_32S
  map[46][3]=119; // [idx] 12C_34S
  map[46][4]=120; // [idx] 13C_34S

  //  Molecule 47, SO3
  map[47][1]=121; // [idx] 32S_16O3
  return rcd; // [enm] Return success code

} // end iso_idx_map_get()

